# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"id_": "id"})
class BaseLeague(BaseModel):
    """BaseLeague

    :param id_: id_
    :type id_: int
    :param image_url: image_url
    :type image_url: str
    :param modified_at: modified_at
    :type modified_at: str
    :param name: name
    :type name: str
    :param slug: slug
    :type slug: str
    :param url: url
    :type url: str
    """

    def __init__(
        self, id_: int, image_url: str, modified_at: str, name: str, slug: str, url: str
    ):
        """BaseLeague

        :param id_: id_
        :type id_: int
        :param image_url: image_url
        :type image_url: str
        :param modified_at: modified_at
        :type modified_at: str
        :param name: name
        :type name: str
        :param slug: slug
        :type slug: str
        :param url: url
        :type url: str
        """
        self.id_ = self._define_number("id_", id_, ge=1)
        self.image_url = self._define_str("image_url", image_url, nullable=True)
        self.modified_at = self._define_str("modified_at", modified_at, min_length=1)
        self.name = name
        self.slug = self._define_str(
            "slug", slug, pattern="^[a-z0-9:_-]+$", min_length=1
        )
        self.url = self._define_str("url", url, nullable=True)
