# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"id_": "id"})
class CsgoMap(BaseModel):
    """CsgoMap

    :param id_: The ID of the map.
    :type id_: int
    :param image_url: A URL to the image of the map.
    :type image_url: str
    :param name: The name of the map.
    :type name: str
    :param slug: Human-readable identifier of the map
    :type slug: str
    """

    def __init__(self, id_: int, image_url: str, name: str, slug: str):
        """CsgoMap

        :param id_: The ID of the map.
        :type id_: int
        :param image_url: A URL to the image of the map.
        :type image_url: str
        :param name: The name of the map.
        :type name: str
        :param slug: Human-readable identifier of the map
        :type slug: str
        """
        self.id_ = self._define_number("id_", id_, ge=1)
        self.image_url = self._define_str("image_url", image_url, nullable=True)
        self.name = name
        self.slug = self._define_str(
            "slug", slug, pattern="^[a-z0-9_-]+$", min_length=1
        )
