# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class CsgoStatsCountsForMatch(BaseModel):
    """CsgoStatsCountsForMatch

    :param assists: Player's number of kill assists for a game
    :type assists: int
    :param deaths: Player's number of deaths
    :type deaths: int
    :param first_kills_diff: First kill difference
    :type first_kills_diff: int
    :param flash_assists: Player's number of flash assists for a game
    :type flash_assists: float
    :param games_draw: Number of games
    :type games_draw: int
    :param games_lost: Number of games
    :type games_lost: int
    :param games_played: Number of games
    :type games_played: int
    :param games_won: Number of games
    :type games_won: int
    :param headshots: Player's number of headshots
    :type headshots: int
    :param k_d_diff: Player's kills deaths difference for a game
    :type k_d_diff: int
    :param kills: Player's number of kills
    :type kills: int
    :param rounds_played: Number of rounds played
    :type rounds_played: int
    """

    def __init__(
        self,
        assists: int,
        deaths: int,
        first_kills_diff: int,
        flash_assists: float,
        games_draw: int,
        games_lost: int,
        games_played: int,
        games_won: int,
        headshots: int,
        k_d_diff: int,
        kills: int,
        rounds_played: int,
    ):
        """CsgoStatsCountsForMatch

        :param assists: Player's number of kill assists for a game
        :type assists: int
        :param deaths: Player's number of deaths
        :type deaths: int
        :param first_kills_diff: First kill difference
        :type first_kills_diff: int
        :param flash_assists: Player's number of flash assists for a game
        :type flash_assists: float
        :param games_draw: Number of games
        :type games_draw: int
        :param games_lost: Number of games
        :type games_lost: int
        :param games_played: Number of games
        :type games_played: int
        :param games_won: Number of games
        :type games_won: int
        :param headshots: Player's number of headshots
        :type headshots: int
        :param k_d_diff: Player's kills deaths difference for a game
        :type k_d_diff: int
        :param kills: Player's number of kills
        :type kills: int
        :param rounds_played: Number of rounds played
        :type rounds_played: int
        """
        self.assists = self._define_number("assists", assists, nullable=True, ge=0)
        self.deaths = self._define_number("deaths", deaths, nullable=True, ge=0)
        self.first_kills_diff = self._define_number(
            "first_kills_diff", first_kills_diff, nullable=True
        )
        self.flash_assists = self._define_number(
            "flash_assists", flash_assists, nullable=True, ge=0
        )
        self.games_draw = self._define_number("games_draw", games_draw, ge=0)
        self.games_lost = self._define_number("games_lost", games_lost, ge=0)
        self.games_played = self._define_number("games_played", games_played, ge=0)
        self.games_won = self._define_number("games_won", games_won, ge=0)
        self.headshots = self._define_number(
            "headshots", headshots, nullable=True, ge=0
        )
        self.k_d_diff = self._define_number("k_d_diff", k_d_diff, nullable=True)
        self.kills = self._define_number("kills", kills, nullable=True, ge=0)
        self.rounds_played = self._define_number(
            "rounds_played", rounds_played, nullable=True, ge=0
        )
