# This file was generated by liblab | https://liblab.com/

from enum import Enum


class CsgoEventType(Enum):
    """An enumeration representing different categories.

    :cvar KILL: "kill"
    :vartype KILL: str
    :cvar ROUNDEND: "round_end"
    :vartype ROUNDEND: str
    :cvar ROUNDSTART: "round_start"
    :vartype ROUNDSTART: str
    """

    KILL = "kill"
    ROUNDEND = "round_end"
    ROUNDSTART = "round_start"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, CsgoEventType._member_map_.values()))
