# This file was generated by liblab | https://liblab.com/

from enum import Enum


class CsgoRoundSide(Enum):
    """An enumeration representing different categories.

    :cvar COUNTERTERRORISTS: "counter_terrorists"
    :vartype COUNTERTERRORISTS: str
    :cvar TERRORISTS: "terrorists"
    :vartype TERRORISTS: str
    """

    COUNTERTERRORISTS = "counter_terrorists"
    TERRORISTS = "terrorists"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, CsgoRoundSide._member_map_.values()))
