# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .csgo_round_side import CsgoRoundSide


@JsonMap({})
class CsgoFullRoundWinner(BaseModel):
    """CsgoFullRoundWinner

    :param side: side
    :type side: CsgoRoundSide
    :param team_id: team_id
    :type team_id: int
    :param team_name: The name of the team.
    :type team_name: str
    """

    def __init__(self, side: CsgoRoundSide, team_id: int, team_name: str):
        """CsgoFullRoundWinner

        :param side: side
        :type side: CsgoRoundSide
        :param team_id: team_id
        :type team_id: int
        :param team_name: The name of the team.
        :type team_name: str
        """
        self.side = self._enum_matching(side, CsgoRoundSide.list(), "side")
        self.team_id = self._define_number("team_id", team_id, ge=1)
        self.team_name = team_name
