# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class CsgoRoundsScore(BaseModel):
    """CsgoRoundsScore

    :param score: The round score for the team.
    :type score: int
    :param team_id: team_id
    :type team_id: int
    """

    def __init__(self, score: int, team_id: int):
        """CsgoRoundsScore

        :param score: The round score for the team.
        :type score: int
        :param team_id: team_id
        :type team_id: int
        """
        self.score = self._define_number("score", score, ge=0)
        self.team_id = self._define_number("team_id", team_id, ge=1)
