# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .csgo_round_side import CsgoRoundSide


@JsonMap({"id_": "id"})
class CsgoRoundWinner(BaseModel):
    """CsgoRoundWinner

    :param id_: id_
    :type id_: int
    :param side: side
    :type side: CsgoRoundSide
    """

    def __init__(self, id_: int, side: CsgoRoundSide):
        """CsgoRoundWinner

        :param id_: id_
        :type id_: int
        :param side: side
        :type side: CsgoRoundSide
        """
        self.id_ = self._define_number("id_", id_, ge=1)
        self.side = self._enum_matching(side, CsgoRoundSide.list(), "side")
