# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"id_": "id"})
class Dota2PerHeroAbility(BaseModel):
    """An ability used by a hero in a game

    :param id_: id_
    :type id_: int
    :param image_url: image_url
    :type image_url: str
    :param level: level
    :type level: int
    :param name: name
    :type name: str
    """

    def __init__(self, id_: int, image_url: str, level: int, name: str):
        """An ability used by a hero in a game

        :param id_: id_
        :type id_: int
        :param image_url: image_url
        :type image_url: str
        :param level: level
        :type level: int
        :param name: name
        :type name: str
        """
        self.id_ = self._define_number("id_", id_, ge=1)
        self.image_url = self._define_str("image_url", image_url, nullable=True)
        self.level = self._define_number("level", level, nullable=True, ge=1)
        self.name = self._define_str(
            "name", name, pattern="^[a-z0-9_-]+$", min_length=1
        )
