# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .dota2_team_ratios import Dota2TeamRatios


@JsonMap({})
class Dota2TeamAverages(BaseModel):
    """Dota2TeamAverages

    :param assists: assists
    :type assists: float
    :param barracks: barracks
    :type barracks: float
    :param camps_stacked: The average number of camps stacked by the team
    :type camps_stacked: float
    :param creeps_stacked: creeps_stacked
    :type creeps_stacked: float
    :param damage_taken: The average damage taken by the team
    :type damage_taken: float
    :param deaths: deaths
    :type deaths: float
    :param denies: Average number of denies per game
    :type denies: float
    :param game_length: Duration of the game in seconds. <br/>`null` when the game status is not `finished`
    :type game_length: int
    :param gold_per_min: gold_per_min
    :type gold_per_min: float
    :param gold_spent: The average of the team's gold spent
    :type gold_spent: float
    :param heal: heal
    :type heal: float
    :param hero_damage: hero_damage
    :type hero_damage: float
    :param kills: kills
    :type kills: float
    :param lane_creep: lane_creep
    :type lane_creep: float
    :param last_hits: last_hits
    :type last_hits: float
    :param net_worth: net_worth
    :type net_worth: float
    :param neutral_creep: neutral_creep
    :type neutral_creep: float
    :param observer_used: observer_used
    :type observer_used: float
    :param observer_wards_destroyed: observer_wards_destroyed
    :type observer_wards_destroyed: float
    :param observer_wards_purchased: observer_wards_purchased
    :type observer_wards_purchased: float
    :param ratios: ratios
    :type ratios: Dota2TeamRatios
    :param roshan_kills: The average number of Roshans killed by the team
    :type roshan_kills: float
    :param sentry_used: sentry_used
    :type sentry_used: float
    :param sentry_wards_destroyed: sentry_wards_destroyed
    :type sentry_wards_destroyed: float
    :param sentry_wards_purchased: sentry_wards_purchased
    :type sentry_wards_purchased: float
    :param tower_damage: tower_damage
    :type tower_damage: float
    :param tower_kills: tower_kills
    :type tower_kills: float
    :param xp_per_min: xp_per_min
    :type xp_per_min: float
    """

    def __init__(
        self,
        assists: float,
        barracks: float,
        camps_stacked: float,
        creeps_stacked: float,
        damage_taken: float,
        deaths: float,
        denies: float,
        game_length: int,
        gold_per_min: float,
        gold_spent: float,
        heal: float,
        hero_damage: float,
        kills: float,
        lane_creep: float,
        last_hits: float,
        net_worth: float,
        neutral_creep: float,
        observer_used: float,
        observer_wards_destroyed: float,
        observer_wards_purchased: float,
        ratios: Dota2TeamRatios,
        roshan_kills: float,
        sentry_used: float,
        sentry_wards_destroyed: float,
        sentry_wards_purchased: float,
        tower_damage: float,
        tower_kills: float,
        xp_per_min: float,
    ):
        """Dota2TeamAverages

        :param assists: assists
        :type assists: float
        :param barracks: barracks
        :type barracks: float
        :param camps_stacked: The average number of camps stacked by the team
        :type camps_stacked: float
        :param creeps_stacked: creeps_stacked
        :type creeps_stacked: float
        :param damage_taken: The average damage taken by the team
        :type damage_taken: float
        :param deaths: deaths
        :type deaths: float
        :param denies: Average number of denies per game
        :type denies: float
        :param game_length: Duration of the game in seconds. <br/>`null` when the game status is not `finished`
        :type game_length: int
        :param gold_per_min: gold_per_min
        :type gold_per_min: float
        :param gold_spent: The average of the team's gold spent
        :type gold_spent: float
        :param heal: heal
        :type heal: float
        :param hero_damage: hero_damage
        :type hero_damage: float
        :param kills: kills
        :type kills: float
        :param lane_creep: lane_creep
        :type lane_creep: float
        :param last_hits: last_hits
        :type last_hits: float
        :param net_worth: net_worth
        :type net_worth: float
        :param neutral_creep: neutral_creep
        :type neutral_creep: float
        :param observer_used: observer_used
        :type observer_used: float
        :param observer_wards_destroyed: observer_wards_destroyed
        :type observer_wards_destroyed: float
        :param observer_wards_purchased: observer_wards_purchased
        :type observer_wards_purchased: float
        :param ratios: ratios
        :type ratios: Dota2TeamRatios
        :param roshan_kills: The average number of Roshans killed by the team
        :type roshan_kills: float
        :param sentry_used: sentry_used
        :type sentry_used: float
        :param sentry_wards_destroyed: sentry_wards_destroyed
        :type sentry_wards_destroyed: float
        :param sentry_wards_purchased: sentry_wards_purchased
        :type sentry_wards_purchased: float
        :param tower_damage: tower_damage
        :type tower_damage: float
        :param tower_kills: tower_kills
        :type tower_kills: float
        :param xp_per_min: xp_per_min
        :type xp_per_min: float
        """
        self.assists = self._define_number("assists", assists, nullable=True, ge=0)
        self.barracks = self._define_number("barracks", barracks, nullable=True, ge=0)
        self.camps_stacked = self._define_number(
            "camps_stacked", camps_stacked, nullable=True, ge=0
        )
        self.creeps_stacked = self._define_number(
            "creeps_stacked", creeps_stacked, nullable=True, ge=0
        )
        self.damage_taken = self._define_number(
            "damage_taken", damage_taken, nullable=True, ge=0
        )
        self.deaths = self._define_number("deaths", deaths, nullable=True, ge=0)
        self.denies = self._define_number("denies", denies, nullable=True, ge=0)
        self.game_length = self._define_number(
            "game_length", game_length, nullable=True, ge=0
        )
        self.gold_per_min = self._define_number(
            "gold_per_min", gold_per_min, nullable=True, ge=0
        )
        self.gold_spent = self._define_number(
            "gold_spent", gold_spent, nullable=True, ge=0
        )
        self.heal = self._define_number("heal", heal, nullable=True, ge=0)
        self.hero_damage = self._define_number(
            "hero_damage", hero_damage, nullable=True, ge=0
        )
        self.kills = self._define_number("kills", kills, nullable=True, ge=0)
        self.lane_creep = self._define_number(
            "lane_creep", lane_creep, nullable=True, ge=0
        )
        self.last_hits = self._define_number(
            "last_hits", last_hits, nullable=True, ge=0
        )
        self.net_worth = self._define_number(
            "net_worth", net_worth, nullable=True, ge=0
        )
        self.neutral_creep = self._define_number(
            "neutral_creep", neutral_creep, nullable=True, ge=0
        )
        self.observer_used = self._define_number(
            "observer_used", observer_used, nullable=True, ge=0
        )
        self.observer_wards_destroyed = self._define_number(
            "observer_wards_destroyed", observer_wards_destroyed, nullable=True, ge=0
        )
        self.observer_wards_purchased = self._define_number(
            "observer_wards_purchased", observer_wards_purchased, nullable=True, ge=0
        )
        self.ratios = self._define_object(ratios, Dota2TeamRatios)
        self.roshan_kills = self._define_number(
            "roshan_kills", roshan_kills, nullable=True, ge=0
        )
        self.sentry_used = self._define_number(
            "sentry_used", sentry_used, nullable=True, ge=0
        )
        self.sentry_wards_destroyed = self._define_number(
            "sentry_wards_destroyed", sentry_wards_destroyed, nullable=True, ge=0
        )
        self.sentry_wards_purchased = self._define_number(
            "sentry_wards_purchased", sentry_wards_purchased, nullable=True, ge=0
        )
        self.tower_damage = self._define_number(
            "tower_damage", tower_damage, nullable=True, ge=0
        )
        self.tower_kills = self._define_number(
            "tower_kills", tower_kills, nullable=True, ge=0
        )
        self.xp_per_min = self._define_number(
            "xp_per_min", xp_per_min, nullable=True, ge=0
        )
