# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"id_": "id"})
class Dota2UsedItem(BaseModel):
    """An item used by a hero

    :param count: count
    :type count: int
    :param id_: id_
    :type id_: int
    :param name: name
    :type name: str
    """

    def __init__(self, count: int, id_: int, name: str):
        """An item used by a hero

        :param count: count
        :type count: int
        :param id_: id_
        :type id_: int
        :param name: name
        :type name: str
        """
        self.count = self._define_number("count", count, ge=0)
        self.id_ = self._define_number("id_", id_, ge=1)
        self.name = self._define_str(
            "name", name, pattern="^[a-z0-9_-]+$", min_length=1
        )
