# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class Dota2TeamStatsTotals(BaseModel):
    """Dota2TeamStatsTotals

    :param assists: assists
    :type assists: int
    :param deaths: deaths
    :type deaths: int
    :param dire_games_lost: Number of games
    :type dire_games_lost: int
    :param dire_games_won: Number of games
    :type dire_games_won: int
    :param games_lost: Number of games
    :type games_lost: int
    :param games_played: Number of games
    :type games_played: int
    :param games_won: Number of games
    :type games_won: int
    :param kills: kills
    :type kills: int
    :param matches_draw: matches_draw
    :type matches_draw: int
    :param matches_lost: matches_lost
    :type matches_lost: int
    :param matches_played: matches_played
    :type matches_played: int
    :param matches_won: matches_won
    :type matches_won: int
    :param observer_wards_destroyed: observer_wards_destroyed
    :type observer_wards_destroyed: int
    :param observer_wards_placed: observer_wards_placed
    :type observer_wards_placed: int
    :param radiant_games_lost: Number of games
    :type radiant_games_lost: int
    :param radiant_games_won: Number of games
    :type radiant_games_won: int
    :param roshan_kills: The total number of Roshans killed by the team
    :type roshan_kills: int
    :param sentry_wards_destroyed: sentry_wards_destroyed
    :type sentry_wards_destroyed: int
    :param sentry_wards_placed: sentry_wards_placed
    :type sentry_wards_placed: int
    :param tower_kills: tower_kills
    :type tower_kills: int
    """

    def __init__(
        self,
        assists: int,
        deaths: int,
        dire_games_lost: int,
        dire_games_won: int,
        games_lost: int,
        games_played: int,
        games_won: int,
        kills: int,
        matches_draw: int,
        matches_lost: int,
        matches_played: int,
        matches_won: int,
        observer_wards_destroyed: int,
        observer_wards_placed: int,
        radiant_games_lost: int,
        radiant_games_won: int,
        roshan_kills: int,
        sentry_wards_destroyed: int,
        sentry_wards_placed: int,
        tower_kills: int,
    ):
        """Dota2TeamStatsTotals

        :param assists: assists
        :type assists: int
        :param deaths: deaths
        :type deaths: int
        :param dire_games_lost: Number of games
        :type dire_games_lost: int
        :param dire_games_won: Number of games
        :type dire_games_won: int
        :param games_lost: Number of games
        :type games_lost: int
        :param games_played: Number of games
        :type games_played: int
        :param games_won: Number of games
        :type games_won: int
        :param kills: kills
        :type kills: int
        :param matches_draw: matches_draw
        :type matches_draw: int
        :param matches_lost: matches_lost
        :type matches_lost: int
        :param matches_played: matches_played
        :type matches_played: int
        :param matches_won: matches_won
        :type matches_won: int
        :param observer_wards_destroyed: observer_wards_destroyed
        :type observer_wards_destroyed: int
        :param observer_wards_placed: observer_wards_placed
        :type observer_wards_placed: int
        :param radiant_games_lost: Number of games
        :type radiant_games_lost: int
        :param radiant_games_won: Number of games
        :type radiant_games_won: int
        :param roshan_kills: The total number of Roshans killed by the team
        :type roshan_kills: int
        :param sentry_wards_destroyed: sentry_wards_destroyed
        :type sentry_wards_destroyed: int
        :param sentry_wards_placed: sentry_wards_placed
        :type sentry_wards_placed: int
        :param tower_kills: tower_kills
        :type tower_kills: int
        """
        self.assists = self._define_number("assists", assists, nullable=True, ge=0)
        self.deaths = self._define_number("deaths", deaths, nullable=True, ge=0)
        self.dire_games_lost = self._define_number(
            "dire_games_lost", dire_games_lost, nullable=True, ge=0
        )
        self.dire_games_won = self._define_number(
            "dire_games_won", dire_games_won, nullable=True, ge=0
        )
        self.games_lost = self._define_number(
            "games_lost", games_lost, nullable=True, ge=0
        )
        self.games_played = self._define_number(
            "games_played", games_played, nullable=True, ge=0
        )
        self.games_won = self._define_number(
            "games_won", games_won, nullable=True, ge=0
        )
        self.kills = self._define_number("kills", kills, nullable=True, ge=0)
        self.matches_draw = self._define_number("matches_draw", matches_draw, ge=0)
        self.matches_lost = self._define_number(
            "matches_lost", matches_lost, nullable=True, ge=0
        )
        self.matches_played = self._define_number(
            "matches_played", matches_played, nullable=True, ge=0
        )
        self.matches_won = self._define_number(
            "matches_won", matches_won, nullable=True, ge=0
        )
        self.observer_wards_destroyed = self._define_number(
            "observer_wards_destroyed", observer_wards_destroyed, nullable=True, ge=0
        )
        self.observer_wards_placed = self._define_number(
            "observer_wards_placed", observer_wards_placed, nullable=True, ge=0
        )
        self.radiant_games_lost = self._define_number(
            "radiant_games_lost", radiant_games_lost, nullable=True, ge=0
        )
        self.radiant_games_won = self._define_number(
            "radiant_games_won", radiant_games_won, nullable=True, ge=0
        )
        self.roshan_kills = self._define_number(
            "roshan_kills", roshan_kills, nullable=True, ge=0
        )
        self.sentry_wards_destroyed = self._define_number(
            "sentry_wards_destroyed", sentry_wards_destroyed, nullable=True, ge=0
        )
        self.sentry_wards_placed = self._define_number(
            "sentry_wards_placed", sentry_wards_placed, nullable=True, ge=0
        )
        self.tower_kills = self._define_number(
            "tower_kills", tower_kills, nullable=True, ge=0
        )
