# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class Dota2PlayerAverages(BaseModel):
    """Dota2PlayerAverages

    :param assists: assists
    :type assists: float
    :param camps_stacked: The average number of camps stacked by the team
    :type camps_stacked: float
    :param creeps_stacked: creeps_stacked
    :type creeps_stacked: float
    :param damage_taken: The average damage taken by the team
    :type damage_taken: float
    :param deaths: deaths
    :type deaths: float
    :param denies: Average number of denies per game
    :type denies: float
    :param gold_per_minute: gold_per_minute
    :type gold_per_minute: float
    :param gold_percentage: Percentage of gold (per min) the player had compared to the total gold of the team
    :type gold_percentage: float
    :param heal: heal
    :type heal: float
    :param hero_damage: hero_damage
    :type hero_damage: float
    :param hero_damage_percentage: Percentage of damage to heroes the player had compared to the total damage of the team
    :type hero_damage_percentage: float
    :param kills: kills
    :type kills: float
    :param lane_creep: lane_creep
    :type lane_creep: float
    :param last_hits: last_hits
    :type last_hits: float
    :param net_worth: net_worth
    :type net_worth: float
    :param neutral_creep: neutral_creep
    :type neutral_creep: float
    :param observer_wards_destroyed: observer_wards_destroyed
    :type observer_wards_destroyed: float
    :param observer_wards_placed: observer_wards_placed
    :type observer_wards_placed: float
    :param observer_wards_purchased: observer_wards_purchased
    :type observer_wards_purchased: float
    :param sentry_wards_destroyed: sentry_wards_destroyed
    :type sentry_wards_destroyed: float
    :param sentry_wards_placed: sentry_wards_placed
    :type sentry_wards_placed: float
    :param sentry_wards_purchased: sentry_wards_purchased
    :type sentry_wards_purchased: float
    :param tower_damage: tower_damage
    :type tower_damage: float
    :param tower_kills: tower_kills
    :type tower_kills: float
    :param wards_placed: wards_placed
    :type wards_placed: float
    :param xp_per_minute: xp_per_minute
    :type xp_per_minute: float
    """

    def __init__(
        self,
        assists: float,
        camps_stacked: float,
        creeps_stacked: float,
        damage_taken: float,
        deaths: float,
        denies: float,
        gold_per_minute: float,
        gold_percentage: float,
        heal: float,
        hero_damage: float,
        hero_damage_percentage: float,
        kills: float,
        lane_creep: float,
        last_hits: float,
        net_worth: float,
        neutral_creep: float,
        observer_wards_destroyed: float,
        observer_wards_placed: float,
        observer_wards_purchased: float,
        sentry_wards_destroyed: float,
        sentry_wards_placed: float,
        sentry_wards_purchased: float,
        tower_damage: float,
        tower_kills: float,
        wards_placed: float,
        xp_per_minute: float,
    ):
        """Dota2PlayerAverages

        :param assists: assists
        :type assists: float
        :param camps_stacked: The average number of camps stacked by the team
        :type camps_stacked: float
        :param creeps_stacked: creeps_stacked
        :type creeps_stacked: float
        :param damage_taken: The average damage taken by the team
        :type damage_taken: float
        :param deaths: deaths
        :type deaths: float
        :param denies: Average number of denies per game
        :type denies: float
        :param gold_per_minute: gold_per_minute
        :type gold_per_minute: float
        :param gold_percentage: Percentage of gold (per min) the player had compared to the total gold of the team
        :type gold_percentage: float
        :param heal: heal
        :type heal: float
        :param hero_damage: hero_damage
        :type hero_damage: float
        :param hero_damage_percentage: Percentage of damage to heroes the player had compared to the total damage of the team
        :type hero_damage_percentage: float
        :param kills: kills
        :type kills: float
        :param lane_creep: lane_creep
        :type lane_creep: float
        :param last_hits: last_hits
        :type last_hits: float
        :param net_worth: net_worth
        :type net_worth: float
        :param neutral_creep: neutral_creep
        :type neutral_creep: float
        :param observer_wards_destroyed: observer_wards_destroyed
        :type observer_wards_destroyed: float
        :param observer_wards_placed: observer_wards_placed
        :type observer_wards_placed: float
        :param observer_wards_purchased: observer_wards_purchased
        :type observer_wards_purchased: float
        :param sentry_wards_destroyed: sentry_wards_destroyed
        :type sentry_wards_destroyed: float
        :param sentry_wards_placed: sentry_wards_placed
        :type sentry_wards_placed: float
        :param sentry_wards_purchased: sentry_wards_purchased
        :type sentry_wards_purchased: float
        :param tower_damage: tower_damage
        :type tower_damage: float
        :param tower_kills: tower_kills
        :type tower_kills: float
        :param wards_placed: wards_placed
        :type wards_placed: float
        :param xp_per_minute: xp_per_minute
        :type xp_per_minute: float
        """
        self.assists = self._define_number("assists", assists, nullable=True, ge=0)
        self.camps_stacked = self._define_number(
            "camps_stacked", camps_stacked, nullable=True, ge=0
        )
        self.creeps_stacked = self._define_number(
            "creeps_stacked", creeps_stacked, nullable=True, ge=0
        )
        self.damage_taken = self._define_number(
            "damage_taken", damage_taken, nullable=True, ge=0
        )
        self.deaths = self._define_number("deaths", deaths, nullable=True, ge=0)
        self.denies = self._define_number("denies", denies, nullable=True, ge=0)
        self.gold_per_minute = self._define_number(
            "gold_per_minute", gold_per_minute, ge=0
        )
        self.gold_percentage = self._define_number(
            "gold_percentage", gold_percentage, ge=0, le=100
        )
        self.heal = self._define_number("heal", heal, nullable=True, ge=0)
        self.hero_damage = self._define_number(
            "hero_damage", hero_damage, nullable=True, ge=0
        )
        self.hero_damage_percentage = self._define_number(
            "hero_damage_percentage",
            hero_damage_percentage,
            nullable=True,
            ge=0,
            le=100,
        )
        self.kills = self._define_number("kills", kills, nullable=True, ge=0)
        self.lane_creep = self._define_number(
            "lane_creep", lane_creep, nullable=True, ge=0
        )
        self.last_hits = self._define_number(
            "last_hits", last_hits, nullable=True, ge=0
        )
        self.net_worth = self._define_number(
            "net_worth", net_worth, nullable=True, ge=0
        )
        self.neutral_creep = self._define_number(
            "neutral_creep", neutral_creep, nullable=True, ge=0
        )
        self.observer_wards_destroyed = self._define_number(
            "observer_wards_destroyed", observer_wards_destroyed, nullable=True, ge=0
        )
        self.observer_wards_placed = self._define_number(
            "observer_wards_placed", observer_wards_placed, nullable=True, ge=0
        )
        self.observer_wards_purchased = self._define_number(
            "observer_wards_purchased", observer_wards_purchased, nullable=True, ge=0
        )
        self.sentry_wards_destroyed = self._define_number(
            "sentry_wards_destroyed", sentry_wards_destroyed, nullable=True, ge=0
        )
        self.sentry_wards_placed = self._define_number(
            "sentry_wards_placed", sentry_wards_placed, nullable=True, ge=0
        )
        self.sentry_wards_purchased = self._define_number(
            "sentry_wards_purchased", sentry_wards_purchased, nullable=True, ge=0
        )
        self.tower_damage = self._define_number(
            "tower_damage", tower_damage, nullable=True, ge=0
        )
        self.tower_kills = self._define_number(
            "tower_kills", tower_kills, nullable=True, ge=0
        )
        self.wards_placed = self._define_number(
            "wards_placed", wards_placed, nullable=True, ge=0
        )
        self.xp_per_minute = self._define_number("xp_per_minute", xp_per_minute, ge=0)
