# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from typing import Union
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.one_of_base_model import OneOfBaseModel
from .dota2_per_hero_ability import Dota2PerHeroAbility
from .dota2_item import Dota2Item
from .base_player import BasePlayer


class Dota2FullGamePlayerFaction(Enum):
    """An enumeration representing different categories.

    :cvar DIRE: "dire"
    :vartype DIRE: str
    :cvar RADIANT: "radiant"
    :vartype RADIANT: str
    """

    DIRE = "dire"
    RADIANT = "radiant"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, Dota2FullGamePlayerFaction._member_map_.values())
        )


@JsonMap({"id_": "id"})
class Dota2FullGamePlayerHero(BaseModel):
    """Dota2FullGamePlayerHero

    :param id_: id_
    :type id_: int
    :param image_url: image_url
    :type image_url: str
    :param localized_name: localized_name
    :type localized_name: str
    :param name: name
    :type name: str
    """

    def __init__(self, id_: int, image_url: str, localized_name: str, name: str):
        """Dota2FullGamePlayerHero

        :param id_: id_
        :type id_: int
        :param image_url: image_url
        :type image_url: str
        :param localized_name: localized_name
        :type localized_name: str
        :param name: name
        :type name: str
        """
        self.id_ = self._define_number("id_", id_, ge=1)
        self.image_url = self._define_str("image_url", image_url, nullable=True)
        self.localized_name = localized_name
        self.name = self._define_str(
            "name", name, pattern="^[a-z0-9_-]+$", min_length=1
        )


@JsonMap({"id_": "id"})
class Opponent1_1(BaseModel):
    """Opponent1_1

    :param active: Whether player is active
    :type active: bool
    :param age: Age of the player, `null` if unknown. When `birthday` is `null`, `age` is an approxiamation. Read more about [players' age](/docs/about-players-age) <br/>**Note**: This field is only present for users running the Historical plan or above.
    :type age: float
    :param birthday: Birth day of the player, `YYYY-MM-DD` format. `null` if unknown. <br/>**Note**: This field is only present for users running the Historical plan or above.
    :type birthday: str
    :param first_name: First name of the player. `null` if unknown
    :type first_name: str
    :param id_: ID of the player
    :type id_: int
    :param image_url: URL to the photo of the player. `null` if not available.
    :type image_url: str
    :param last_name: Last name of the player. `null` if unknown
    :type last_name: str
    :param modified_at: modified_at
    :type modified_at: str
    :param name: Professional name of the player
    :type name: str
    :param nationality: Country code matching the nationality of the player according to the ISO 3166-1 standard (Alpha-2 code). <br/>In addition to the standard, the `XK` code is used for Kosovo. <br/>`null` if unknown
    :type nationality: str
    :param role: Role/position of the player. Field value varies depending on the video game.`null` if unknown. <br/>**Note**: role is only available for DotA 2, League of Legends, and Overwatch players. <br/>`null` for other video games.
    :type role: str
    :param slug: Unique, human-readable identifier for the player. <br/>`id` and `slug` can be used interchangeably throughout the API.
    :type slug: str
    """

    def __init__(
        self,
        active: bool,
        age: float,
        birthday: str,
        first_name: str,
        id_: int,
        image_url: str,
        last_name: str,
        modified_at: str,
        name: str,
        nationality: str,
        role: str,
        slug: str,
    ):
        """Opponent1_1

        :param active: Whether player is active
        :type active: bool
        :param age: Age of the player, `null` if unknown. When `birthday` is `null`, `age` is an approxiamation. Read more about [players' age](/docs/about-players-age) <br/>**Note**: This field is only present for users running the Historical plan or above.
        :type age: float
        :param birthday: Birth day of the player, `YYYY-MM-DD` format. `null` if unknown. <br/>**Note**: This field is only present for users running the Historical plan or above.
        :type birthday: str
        :param first_name: First name of the player. `null` if unknown
        :type first_name: str
        :param id_: ID of the player
        :type id_: int
        :param image_url: URL to the photo of the player. `null` if not available.
        :type image_url: str
        :param last_name: Last name of the player. `null` if unknown
        :type last_name: str
        :param modified_at: modified_at
        :type modified_at: str
        :param name: Professional name of the player
        :type name: str
        :param nationality: Country code matching the nationality of the player according to the ISO 3166-1 standard (Alpha-2 code). <br/>In addition to the standard, the `XK` code is used for Kosovo. <br/>`null` if unknown
        :type nationality: str
        :param role: Role/position of the player. Field value varies depending on the video game.`null` if unknown. <br/>**Note**: role is only available for DotA 2, League of Legends, and Overwatch players. <br/>`null` for other video games.
        :type role: str
        :param slug: Unique, human-readable identifier for the player. <br/>`id` and `slug` can be used interchangeably throughout the API.
        :type slug: str
        """
        self.active = active
        self.age = self._define_number("age", age, nullable=True, ge=0)
        self.birthday = self._define_str("birthday", birthday, nullable=True)
        self.first_name = self._define_str("first_name", first_name, nullable=True)
        self.id_ = self._define_number("id_", id_, ge=1)
        self.image_url = self._define_str("image_url", image_url, nullable=True)
        self.last_name = self._define_str("last_name", last_name, nullable=True)
        self.modified_at = self._define_str("modified_at", modified_at, min_length=1)
        self.name = name
        self.nationality = self._define_str("nationality", nationality, nullable=True)
        self.role = self._define_str("role", role, nullable=True)
        self.slug = self._define_str(
            "slug", slug, nullable=True, pattern="^[a-z0-9_-]+$", min_length=1
        )


@JsonMap({"id_": "id"})
class Opponent2_1(BaseModel):
    """Opponent2_1

    :param acronym: acronym
    :type acronym: str
    :param id_: id_
    :type id_: int
    :param image_url: URL of the team logo
    :type image_url: str
    :param location: The team's organization location
    :type location: str
    :param modified_at: modified_at
    :type modified_at: str
    :param name: The name of the team.
    :type name: str
    :param slug: slug
    :type slug: str
    """

    def __init__(
        self,
        acronym: str,
        id_: int,
        image_url: str,
        location: str,
        modified_at: str,
        name: str,
        slug: str,
    ):
        """Opponent2_1

        :param acronym: acronym
        :type acronym: str
        :param id_: id_
        :type id_: int
        :param image_url: URL of the team logo
        :type image_url: str
        :param location: The team's organization location
        :type location: str
        :param modified_at: modified_at
        :type modified_at: str
        :param name: The name of the team.
        :type name: str
        :param slug: slug
        :type slug: str
        """
        self.acronym = self._define_str("acronym", acronym, nullable=True)
        self.id_ = self._define_number("id_", id_, ge=1)
        self.image_url = self._define_str("image_url", image_url, nullable=True)
        self.location = self._define_str("location", location, nullable=True)
        self.modified_at = self._define_str("modified_at", modified_at, min_length=1)
        self.name = name
        self.slug = self._define_str(
            "slug", slug, nullable=True, pattern="^[a-z0-9_-]+$", min_length=1
        )


class Dota2FullGamePlayerOpponentGuard(OneOfBaseModel):
    class_list = {"Opponent1_1": Opponent1_1, "Opponent2_1": Opponent2_1}


Dota2FullGamePlayerOpponent = Union[Opponent1_1, Opponent2_1]


@JsonMap({"id_": "id"})
class Dota2FullGamePlayerTeam(BaseModel):
    """Dota2FullGamePlayerTeam

    :param acronym: acronym
    :type acronym: str
    :param id_: id_
    :type id_: int
    :param image_url: URL of the team logo
    :type image_url: str
    :param location: The team's organization location
    :type location: str
    :param modified_at: modified_at
    :type modified_at: str
    :param name: The name of the team.
    :type name: str
    :param slug: slug
    :type slug: str
    """

    def __init__(
        self,
        acronym: str,
        id_: int,
        image_url: str,
        location: str,
        modified_at: str,
        name: str,
        slug: str,
    ):
        """Dota2FullGamePlayerTeam

        :param acronym: acronym
        :type acronym: str
        :param id_: id_
        :type id_: int
        :param image_url: URL of the team logo
        :type image_url: str
        :param location: The team's organization location
        :type location: str
        :param modified_at: modified_at
        :type modified_at: str
        :param name: The name of the team.
        :type name: str
        :param slug: slug
        :type slug: str
        """
        self.acronym = self._define_str("acronym", acronym, nullable=True)
        self.id_ = self._define_number("id_", id_, ge=1)
        self.image_url = self._define_str("image_url", image_url, nullable=True)
        self.location = self._define_str("location", location, nullable=True)
        self.modified_at = self._define_str("modified_at", modified_at, min_length=1)
        self.name = name
        self.slug = self._define_str(
            "slug", slug, nullable=True, pattern="^[a-z0-9_-]+$", min_length=1
        )


@JsonMap({})
class Dota2FullGamePlayer(BaseModel):
    """Player's data for a game

    :param abilities: abilities
    :type abilities: List[Dota2PerHeroAbility]
    :param assists: Player's number of assists for a game
    :type assists: int
    :param camps_stacked: camps_stacked
    :type camps_stacked: int
    :param creeps_stacked: creeps_stacked
    :type creeps_stacked: int
    :param damage_taken: damage_taken
    :type damage_taken: int
    :param deaths: deaths
    :type deaths: int
    :param denies: Number of denies performed by a player
    :type denies: int
    :param faction: faction
    :type faction: Dota2FullGamePlayerFaction
    :param game_id: game_id
    :type game_id: int
    :param gold_per_min: gold_per_min
    :type gold_per_min: int
    :param gold_percentage: Percentage of gold (per min) the player had compared to the total gold of the team
    :type gold_percentage: float
    :param gold_remaining: gold_remaining
    :type gold_remaining: int
    :param gold_spent: gold_spent
    :type gold_spent: int
    :param heal: Healing (in HP) performed by the player
    :type heal: int
    :param hero: hero
    :type hero: Dota2FullGamePlayerHero
    :param hero_damage: hero_damage
    :type hero_damage: int
    :param hero_damage_percentage: hero_damage_percentage
    :type hero_damage_percentage: float
    :param hero_level: hero_level
    :type hero_level: int
    :param items: items
    :type items: List[Dota2Item]
    :param kills: kills
    :type kills: int
    :param lane_creep: lane_creep
    :type lane_creep: int
    :param last_hits: last_hits
    :type last_hits: int
    :param net_worth: Net worth of the player
    :type net_worth: int
    :param neutral_creep: neutral_creep
    :type neutral_creep: int
    :param observer_used: observer_used
    :type observer_used: int
    :param observer_wards_destroyed: observer_wards_destroyed
    :type observer_wards_destroyed: int
    :param observer_wards_purchased: observer_wards_purchased
    :type observer_wards_purchased: int
    :param opponent: opponent
    :type opponent: Dota2FullGamePlayerOpponent
    :param player: player
    :type player: BasePlayer
    :param role: Position of the player (1, 2, 3, 4, 5)
    :type role: int
    :param sentry_used: sentry_used
    :type sentry_used: int
    :param sentry_wards_destroyed: sentry_wards_destroyed
    :type sentry_wards_destroyed: int
    :param sentry_wards_purchased: sentry_wards_purchased
    :type sentry_wards_purchased: int
    :param team: team
    :type team: Dota2FullGamePlayerTeam
    :param team_id: team_id
    :type team_id: int
    :param tower_damage: tower_damage
    :type tower_damage: int
    :param tower_kills: tower_kills
    :type tower_kills: int
    :param xp_per_min: xp_per_min
    :type xp_per_min: int
    """

    def __init__(
        self,
        abilities: List[Dota2PerHeroAbility],
        assists: int,
        camps_stacked: int,
        creeps_stacked: int,
        damage_taken: int,
        deaths: int,
        denies: int,
        faction: Dota2FullGamePlayerFaction,
        game_id: int,
        gold_per_min: int,
        gold_percentage: float,
        gold_remaining: int,
        gold_spent: int,
        heal: int,
        hero: Dota2FullGamePlayerHero,
        hero_damage: int,
        hero_damage_percentage: float,
        hero_level: int,
        items: List[Dota2Item],
        kills: int,
        lane_creep: int,
        last_hits: int,
        net_worth: int,
        neutral_creep: int,
        observer_used: int,
        observer_wards_destroyed: int,
        observer_wards_purchased: int,
        opponent: Dota2FullGamePlayerOpponent,
        player: BasePlayer,
        role: int,
        sentry_used: int,
        sentry_wards_destroyed: int,
        sentry_wards_purchased: int,
        team: Dota2FullGamePlayerTeam,
        team_id: int,
        tower_damage: int,
        tower_kills: int,
        xp_per_min: int,
    ):
        """Player's data for a game

        :param abilities: abilities
        :type abilities: List[Dota2PerHeroAbility]
        :param assists: Player's number of assists for a game
        :type assists: int
        :param camps_stacked: camps_stacked
        :type camps_stacked: int
        :param creeps_stacked: creeps_stacked
        :type creeps_stacked: int
        :param damage_taken: damage_taken
        :type damage_taken: int
        :param deaths: deaths
        :type deaths: int
        :param denies: Number of denies performed by a player
        :type denies: int
        :param faction: faction
        :type faction: Dota2FullGamePlayerFaction
        :param game_id: game_id
        :type game_id: int
        :param gold_per_min: gold_per_min
        :type gold_per_min: int
        :param gold_percentage: Percentage of gold (per min) the player had compared to the total gold of the team
        :type gold_percentage: float
        :param gold_remaining: gold_remaining
        :type gold_remaining: int
        :param gold_spent: gold_spent
        :type gold_spent: int
        :param heal: Healing (in HP) performed by the player
        :type heal: int
        :param hero: hero
        :type hero: Dota2FullGamePlayerHero
        :param hero_damage: hero_damage
        :type hero_damage: int
        :param hero_damage_percentage: hero_damage_percentage
        :type hero_damage_percentage: float
        :param hero_level: hero_level
        :type hero_level: int
        :param items: items
        :type items: List[Dota2Item]
        :param kills: kills
        :type kills: int
        :param lane_creep: lane_creep
        :type lane_creep: int
        :param last_hits: last_hits
        :type last_hits: int
        :param net_worth: Net worth of the player
        :type net_worth: int
        :param neutral_creep: neutral_creep
        :type neutral_creep: int
        :param observer_used: observer_used
        :type observer_used: int
        :param observer_wards_destroyed: observer_wards_destroyed
        :type observer_wards_destroyed: int
        :param observer_wards_purchased: observer_wards_purchased
        :type observer_wards_purchased: int
        :param opponent: opponent
        :type opponent: Dota2FullGamePlayerOpponent
        :param player: player
        :type player: BasePlayer
        :param role: Position of the player (1, 2, 3, 4, 5)
        :type role: int
        :param sentry_used: sentry_used
        :type sentry_used: int
        :param sentry_wards_destroyed: sentry_wards_destroyed
        :type sentry_wards_destroyed: int
        :param sentry_wards_purchased: sentry_wards_purchased
        :type sentry_wards_purchased: int
        :param team: team
        :type team: Dota2FullGamePlayerTeam
        :param team_id: team_id
        :type team_id: int
        :param tower_damage: tower_damage
        :type tower_damage: int
        :param tower_kills: tower_kills
        :type tower_kills: int
        :param xp_per_min: xp_per_min
        :type xp_per_min: int
        """
        self.abilities = self._define_list(abilities, Dota2PerHeroAbility)
        self.assists = self._define_number("assists", assists, nullable=True, ge=0)
        self.camps_stacked = self._define_number(
            "camps_stacked", camps_stacked, nullable=True, ge=0
        )
        self.creeps_stacked = self._define_number(
            "creeps_stacked", creeps_stacked, nullable=True, ge=0
        )
        self.damage_taken = self._define_number(
            "damage_taken", damage_taken, nullable=True, ge=0
        )
        self.deaths = self._define_number("deaths", deaths, nullable=True, ge=0)
        self.denies = self._define_number("denies", denies, nullable=True, ge=0)
        self.faction = self._enum_matching(
            faction, Dota2FullGamePlayerFaction.list(), "faction"
        )
        self.game_id = self._define_number("game_id", game_id, ge=1)
        self.gold_per_min = self._define_number(
            "gold_per_min", gold_per_min, nullable=True, ge=0
        )
        self.gold_percentage = self._define_number(
            "gold_percentage", gold_percentage, ge=0, le=100
        )
        self.gold_remaining = self._define_number(
            "gold_remaining", gold_remaining, nullable=True, ge=0
        )
        self.gold_spent = self._define_number(
            "gold_spent", gold_spent, nullable=True, ge=0
        )
        self.heal = self._define_number("heal", heal, nullable=True, ge=0)
        self.hero = self._define_object(hero, Dota2FullGamePlayerHero)
        self.hero_damage = self._define_number(
            "hero_damage", hero_damage, nullable=True, ge=0
        )
        self.hero_damage_percentage = self._define_number(
            "hero_damage_percentage", hero_damage_percentage, nullable=True, ge=0
        )
        self.hero_level = self._define_number(
            "hero_level", hero_level, nullable=True, ge=1
        )
        self.items = self._define_list(items, Dota2Item)
        self.kills = self._define_number("kills", kills, nullable=True, ge=0)
        self.lane_creep = self._define_number(
            "lane_creep", lane_creep, nullable=True, ge=0
        )
        self.last_hits = self._define_number(
            "last_hits", last_hits, nullable=True, ge=0
        )
        self.net_worth = self._define_number(
            "net_worth", net_worth, nullable=True, ge=0
        )
        self.neutral_creep = self._define_number(
            "neutral_creep", neutral_creep, nullable=True, ge=0
        )
        self.observer_used = self._define_number(
            "observer_used", observer_used, nullable=True, ge=0
        )
        self.observer_wards_destroyed = self._define_number(
            "observer_wards_destroyed", observer_wards_destroyed, nullable=True, ge=0
        )
        self.observer_wards_purchased = self._define_number(
            "observer_wards_purchased", observer_wards_purchased, nullable=True, ge=0
        )
        self.opponent = Dota2FullGamePlayerOpponentGuard.return_one_of(opponent)
        self.player = self._define_object(player, BasePlayer)
        self.role = self._define_number("role", role, nullable=True, ge=1, le=5)
        self.sentry_used = self._define_number(
            "sentry_used", sentry_used, nullable=True, ge=0
        )
        self.sentry_wards_destroyed = self._define_number(
            "sentry_wards_destroyed", sentry_wards_destroyed, nullable=True, ge=0
        )
        self.sentry_wards_purchased = self._define_number(
            "sentry_wards_purchased", sentry_wards_purchased, nullable=True, ge=0
        )
        self.team = self._define_object(team, Dota2FullGamePlayerTeam)
        self.team_id = self._define_number("team_id", team_id, nullable=True, ge=1)
        self.tower_damage = self._define_number(
            "tower_damage", tower_damage, nullable=True, ge=0
        )
        self.tower_kills = self._define_number(
            "tower_kills", tower_kills, nullable=True, ge=0
        )
        self.xp_per_min = self._define_number(
            "xp_per_min", xp_per_min, nullable=True, ge=0
        )
