# This file was generated by liblab | https://liblab.com/

from typing import Union
from .utils.one_of_base_model import OneOfBaseModel


class GameIdGuard(OneOfBaseModel):
    class_list = {
        "int": int,
        "int": int,
        "int": int,
        "int": int,
        "int": int,
        "int": int,
    }


GameId = Union[int, int, int, int, int, int]
