# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"id_": "id"})
class LeagueVideogameCsgo(BaseModel):
    """LeagueVideogameCsgo

    :param current_version: current_version
    :type current_version: str
    :param id_: id_
    :type id_: any
    :param name: name
    :type name: any
    :param slug: slug
    :type slug: any
    """

    def __init__(self, current_version: str, id_: any, name: any, slug: any):
        """LeagueVideogameCsgo

        :param current_version: current_version
        :type current_version: str
        :param id_: id_
        :type id_: any
        :param name: name
        :type name: any
        :param slug: slug
        :type slug: any
        """
        self.current_version = self._define_str(
            "current_version",
            current_version,
            nullable=True,
            pattern="^[0-9]+\.[0-9]+(\.[0-9]+)?$",
        )
        self.id_ = id_
        self.name = name
        self.slug = slug
