# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class LoLGamePlayerDamageForStats(BaseModel):
    """LoLGamePlayerDamageForStats

    :param dealt: dealt
    :type dealt: int
    :param dealt_to_champions: dealt_to_champions
    :type dealt_to_champions: int
    :param taken: taken
    :type taken: int
    """

    def __init__(self, dealt: int, dealt_to_champions: int, taken: int):
        """LoLGamePlayerDamageForStats

        :param dealt: dealt
        :type dealt: int
        :param dealt_to_champions: dealt_to_champions
        :type dealt_to_champions: int
        :param taken: taken
        :type taken: int
        """
        self.dealt = self._define_number("dealt", dealt, nullable=True, ge=0)
        self.dealt_to_champions = self._define_number(
            "dealt_to_champions", dealt_to_champions, nullable=True, ge=0
        )
        self.taken = self._define_number("taken", taken, nullable=True, ge=0)
