# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .base_lo_l_champion import BaseLoLChampion
from .base_lo_l_spell import BaseLoLSpell


@JsonMap({"id_": "id"})
class LoLPlayersRoleDetail(BaseModel):
    """LoLPlayersRoleDetail

    :param assists: assists
    :type assists: int
    :param champion: champion
    :type champion: BaseLoLChampion
    :param cs: The player's Creep Score (CS.) <br/> <br/>NB: Creep Score can be different that the number of minions killed because neutral monsters can give more score.
    :type cs: int
    :param deaths: deaths
    :type deaths: int
    :param id_: ID of the player
    :type id_: int
    :param kills: kills
    :type kills: int
    :param level: level
    :type level: int
    :param name: Professional name of the player
    :type name: str
    :param summoner_spells: summoner_spells
    :type summoner_spells: List[BaseLoLSpell]
    """

    def __init__(
        self,
        assists: int,
        champion: BaseLoLChampion,
        cs: int,
        deaths: int,
        id_: int,
        kills: int,
        level: int,
        name: str,
        summoner_spells: List[BaseLoLSpell],
    ):
        """LoLPlayersRoleDetail

        :param assists: assists
        :type assists: int
        :param champion: champion
        :type champion: BaseLoLChampion
        :param cs: The player's Creep Score (CS.) <br/> <br/>NB: Creep Score can be different that the number of minions killed because neutral monsters can give more score.
        :type cs: int
        :param deaths: deaths
        :type deaths: int
        :param id_: ID of the player
        :type id_: int
        :param kills: kills
        :type kills: int
        :param level: level
        :type level: int
        :param name: Professional name of the player
        :type name: str
        :param summoner_spells: summoner_spells
        :type summoner_spells: List[BaseLoLSpell]
        """
        self.assists = self._define_number("assists", assists, ge=0)
        self.champion = self._define_object(champion, BaseLoLChampion)
        self.cs = self._define_number("cs", cs, ge=0)
        self.deaths = self._define_number("deaths", deaths, ge=0)
        self.id_ = self._define_number("id_", id_, ge=1)
        self.kills = self._define_number("kills", kills, ge=0)
        self.level = self._define_number("level", level, ge=1)
        self.name = name
        self.summoner_spells = self._define_list(summoner_spells, BaseLoLSpell)
