# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .lo_l_event_neutral_minion_value import LoLEventNeutralMinionValue


@JsonMap({})
class LoLEventNeutralMinionObject(BaseModel):
    """LoLEventNeutralMinionObject

    :param name: name
    :type name: LoLEventNeutralMinionValue
    """

    def __init__(self, name: LoLEventNeutralMinionValue):
        """LoLEventNeutralMinionObject

        :param name: name
        :type name: LoLEventNeutralMinionValue
        """
        self.name = self._enum_matching(name, LoLEventNeutralMinionValue.list(), "name")
