# This file was generated by liblab | https://liblab.com/

from enum import Enum


class LoLEventNashorValue(Enum):
    """An enumeration representing different categories.

    :cvar BARONNASHOR: "Baron Nashor"
    :vartype BARONNASHOR: str
    """

    BARONNASHOR = "Baron Nashor"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, LoLEventNashorValue._member_map_.values()))
