# This file was generated by liblab | https://liblab.com/

from enum import Enum


class LoLEventNeutralMinionValue(Enum):
    """An enumeration representing different categories.

    :cvar BIGCORBIN: "Big Corbin"
    :vartype BIGCORBIN: str
    :cvar BIGGOLEM: "Big Golem"
    :vartype BIGGOLEM: str
    :cvar BIGWOLF: "Big Wolf"
    :vartype BIGWOLF: str
    :cvar BLUEBUFF: "Blue Buff"
    :vartype BLUEBUFF: str
    :cvar GROMP: "Gromp"
    :vartype GROMP: str
    :cvar REDBUFF: "Red Buff"
    :vartype REDBUFF: str
    :cvar SMALLCORBIN: "Small Corbin"
    :vartype SMALLCORBIN: str
    :cvar SMALLGOLEM: "Small Golem"
    :vartype SMALLGOLEM: str
    :cvar SMALLWOLF: "Small Wolf"
    :vartype SMALLWOLF: str
    """

    BIGCORBIN = "Big Corbin"
    BIGGOLEM = "Big Golem"
    BIGWOLF = "Big Wolf"
    BLUEBUFF = "Blue Buff"
    GROMP = "Gromp"
    REDBUFF = "Red Buff"
    SMALLCORBIN = "Small Corbin"
    SMALLGOLEM = "Small Golem"
    SMALLWOLF = "Small Wolf"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, LoLEventNeutralMinionValue._member_map_.values())
        )
