# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class LoLAverageTrueDamage(BaseModel):
    """LoLAverageTrueDamage

    :param dealt: dealt
    :type dealt: float
    :param dealt_percentage: Percentage of damage dealt the player had compared to the total damage of the team
    :type dealt_percentage: float
    :param dealt_to_champions: dealt_to_champions
    :type dealt_to_champions: float
    :param dealt_to_champions_percentage: Percentage of damage dealt to champions the player had compared to the total damage of the team
    :type dealt_to_champions_percentage: float
    :param taken: taken
    :type taken: float
    """

    def __init__(
        self,
        dealt: float,
        dealt_percentage: float,
        dealt_to_champions: float,
        dealt_to_champions_percentage: float,
        taken: float,
    ):
        """LoLAverageTrueDamage

        :param dealt: dealt
        :type dealt: float
        :param dealt_percentage: Percentage of damage dealt the player had compared to the total damage of the team
        :type dealt_percentage: float
        :param dealt_to_champions: dealt_to_champions
        :type dealt_to_champions: float
        :param dealt_to_champions_percentage: Percentage of damage dealt to champions the player had compared to the total damage of the team
        :type dealt_to_champions_percentage: float
        :param taken: taken
        :type taken: float
        """
        self.dealt = self._define_number("dealt", dealt, nullable=True, ge=0)
        self.dealt_percentage = self._define_number(
            "dealt_percentage", dealt_percentage, nullable=True, ge=0, le=100
        )
        self.dealt_to_champions = self._define_number(
            "dealt_to_champions", dealt_to_champions, nullable=True, ge=0
        )
        self.dealt_to_champions_percentage = self._define_number(
            "dealt_to_champions_percentage",
            dealt_to_champions_percentage,
            nullable=True,
            ge=0,
            le=100,
        )
        self.taken = self._define_number("taken", taken, nullable=True, ge=0)
