# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .lo_l_players_role import LoLPlayersRole


@JsonMap({"id_": "id"})
class LoLFrameTeam(BaseModel):
    """LoLFrameTeam

    :param acronym: acronym
    :type acronym: str
    :param drakes: drakes
    :type drakes: int
    :param gold: gold
    :type gold: int
    :param id_: id_
    :type id_: int
    :param inhibitors: Number of inhibitors killed by the player
    :type inhibitors: int
    :param kills: kills
    :type kills: int
    :param name: The name of the team.
    :type name: str
    :param nashors: nashors
    :type nashors: int
    :param players: players
    :type players: LoLPlayersRole
    :param score: score
    :type score: int
    :param towers: towers
    :type towers: int
    :param voidgrubs: The number of voidgrubs killed by a team.
    :type voidgrubs: int
    """

    def __init__(
        self,
        acronym: str,
        drakes: int,
        gold: int,
        id_: int,
        inhibitors: int,
        kills: int,
        name: str,
        nashors: int,
        players: LoLPlayersRole,
        score: int,
        towers: int,
        voidgrubs: int,
    ):
        """LoLFrameTeam

        :param acronym: acronym
        :type acronym: str
        :param drakes: drakes
        :type drakes: int
        :param gold: gold
        :type gold: int
        :param id_: id_
        :type id_: int
        :param inhibitors: Number of inhibitors killed by the player
        :type inhibitors: int
        :param kills: kills
        :type kills: int
        :param name: The name of the team.
        :type name: str
        :param nashors: nashors
        :type nashors: int
        :param players: players
        :type players: LoLPlayersRole
        :param score: score
        :type score: int
        :param towers: towers
        :type towers: int
        :param voidgrubs: The number of voidgrubs killed by a team.
        :type voidgrubs: int
        """
        self.acronym = acronym
        self.drakes = self._define_number("drakes", drakes, ge=0)
        self.gold = self._define_number("gold", gold, ge=0)
        self.id_ = self._define_number("id_", id_, ge=1)
        self.inhibitors = self._define_number("inhibitors", inhibitors, ge=0)
        self.kills = self._define_number("kills", kills, ge=0)
        self.name = name
        self.nashors = self._define_number("nashors", nashors, ge=0)
        self.players = self._define_object(players, LoLPlayersRole)
        self.score = self._define_number("score", score, ge=0)
        self.towers = self._define_number("towers", towers, ge=0)
        self.voidgrubs = self._define_number(
            "voidgrubs", voidgrubs, nullable=True, ge=0, le=6
        )
