# This file was generated by liblab | https://liblab.com/

from enum import Enum


class LoLDrakeName(Enum):
    """An enumeration representing different categories.

    :cvar CHEMTECHDRAKE: "Chemtech Drake"
    :vartype CHEMTECHDRAKE: str
    :cvar CLOUDDRAKE: "Cloud Drake"
    :vartype CLOUDDRAKE: str
    :cvar ELDERDRAKE: "Elder Drake"
    :vartype ELDERDRAKE: str
    :cvar HEXTECHDRAKE: "Hextech Drake"
    :vartype HEXTECHDRAKE: str
    :cvar INFERNALDRAKE: "Infernal Drake"
    :vartype INFERNALDRAKE: str
    :cvar MOUNTAINDRAKE: "Mountain Drake"
    :vartype MOUNTAINDRAKE: str
    :cvar OCEANDRAKE: "Ocean Drake"
    :vartype OCEANDRAKE: str
    """

    CHEMTECHDRAKE = "Chemtech Drake"
    CLOUDDRAKE = "Cloud Drake"
    ELDERDRAKE = "Elder Drake"
    HEXTECHDRAKE = "Hextech Drake"
    INFERNALDRAKE = "Infernal Drake"
    MOUNTAINDRAKE = "Mountain Drake"
    OCEANDRAKE = "Ocean Drake"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, LoLDrakeName._member_map_.values()))
