# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class LoLTeamRatios(BaseModel):
    """LoLTeamRatios

    :param first_baron: first_baron
    :type first_baron: float
    :param first_blood: first_blood
    :type first_blood: float
    :param first_dragon: first_dragon
    :type first_dragon: float
    :param first_herald: first_herald
    :type first_herald: float
    :param first_inhibitor: first_inhibitor
    :type first_inhibitor: float
    :param first_tower: first_tower
    :type first_tower: float
    :param first_voidgrub: Whether the team killed the first voidgrub.
    :type first_voidgrub: float
    :param win: win
    :type win: float
    """

    def __init__(
        self,
        first_baron: float,
        first_blood: float,
        first_dragon: float,
        first_herald: float,
        first_inhibitor: float,
        first_tower: float,
        first_voidgrub: float,
        win: float,
    ):
        """LoLTeamRatios

        :param first_baron: first_baron
        :type first_baron: float
        :param first_blood: first_blood
        :type first_blood: float
        :param first_dragon: first_dragon
        :type first_dragon: float
        :param first_herald: first_herald
        :type first_herald: float
        :param first_inhibitor: first_inhibitor
        :type first_inhibitor: float
        :param first_tower: first_tower
        :type first_tower: float
        :param first_voidgrub: Whether the team killed the first voidgrub.
        :type first_voidgrub: float
        :param win: win
        :type win: float
        """
        self.first_baron = self._define_number(
            "first_baron", first_baron, nullable=True, ge=0, le=1
        )
        self.first_blood = self._define_number(
            "first_blood", first_blood, nullable=True, ge=0, le=1
        )
        self.first_dragon = self._define_number(
            "first_dragon", first_dragon, nullable=True, ge=0, le=1
        )
        self.first_herald = self._define_number(
            "first_herald", first_herald, nullable=True, ge=0, le=1
        )
        self.first_inhibitor = self._define_number(
            "first_inhibitor", first_inhibitor, nullable=True, ge=0, le=1
        )
        self.first_tower = self._define_number(
            "first_tower", first_tower, nullable=True, ge=0, le=1
        )
        self.first_voidgrub = self._define_number(
            "first_voidgrub", first_voidgrub, nullable=True, ge=0
        )
        self.win = self._define_number("win", win, nullable=True, ge=0, le=1)
