# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class LoLWards(BaseModel):
    """LoLWards

    :param placed: placed
    :type placed: int
    :param sight_wards_bought_in_game: sight_wards_bought_in_game
    :type sight_wards_bought_in_game: int
    :param vision_wards_bought_in_game: vision_wards_bought_in_game
    :type vision_wards_bought_in_game: int
    """

    def __init__(
        self,
        placed: int,
        sight_wards_bought_in_game: int,
        vision_wards_bought_in_game: int,
    ):
        """LoLWards

        :param placed: placed
        :type placed: int
        :param sight_wards_bought_in_game: sight_wards_bought_in_game
        :type sight_wards_bought_in_game: int
        :param vision_wards_bought_in_game: vision_wards_bought_in_game
        :type vision_wards_bought_in_game: int
        """
        self.placed = self._define_number("placed", placed, nullable=True, ge=0)
        self.sight_wards_bought_in_game = self._define_number(
            "sight_wards_bought_in_game",
            sight_wards_bought_in_game,
            nullable=True,
            ge=0,
        )
        self.vision_wards_bought_in_game = self._define_number(
            "vision_wards_bought_in_game",
            vision_wards_bought_in_game,
            nullable=True,
            ge=0,
        )
