# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .lo_l_player_total_kill_counters import LoLPlayerTotalKillCounters
from .lo_l_kills_series import LoLKillsSeries


@JsonMap({})
class LoLPlayerStatsTotals(BaseModel):
    """LoLPlayerStatsTotals

    :param assists: assists
    :type assists: int
    :param deaths: deaths
    :type deaths: int
    :param games_lost: Number of games
    :type games_lost: int
    :param games_played: Number of games
    :type games_played: int
    :param games_won: Number of games
    :type games_won: int
    :param kill_counters: kill_counters
    :type kill_counters: LoLPlayerTotalKillCounters
    :param kills: kills
    :type kills: int
    :param kills_series: kills_series
    :type kills_series: LoLKillsSeries
    :param matches_lost: matches_lost
    :type matches_lost: int
    :param matches_played: matches_played
    :type matches_played: int
    :param matches_won: matches_won
    :type matches_won: int
    :param wards_placed: wards_placed
    :type wards_placed: int
    """

    def __init__(
        self,
        assists: int,
        deaths: int,
        games_lost: int,
        games_played: int,
        games_won: int,
        kill_counters: LoLPlayerTotalKillCounters,
        kills: int,
        kills_series: LoLKillsSeries,
        matches_lost: int,
        matches_played: int,
        matches_won: int,
        wards_placed: int,
    ):
        """LoLPlayerStatsTotals

        :param assists: assists
        :type assists: int
        :param deaths: deaths
        :type deaths: int
        :param games_lost: Number of games
        :type games_lost: int
        :param games_played: Number of games
        :type games_played: int
        :param games_won: Number of games
        :type games_won: int
        :param kill_counters: kill_counters
        :type kill_counters: LoLPlayerTotalKillCounters
        :param kills: kills
        :type kills: int
        :param kills_series: kills_series
        :type kills_series: LoLKillsSeries
        :param matches_lost: matches_lost
        :type matches_lost: int
        :param matches_played: matches_played
        :type matches_played: int
        :param matches_won: matches_won
        :type matches_won: int
        :param wards_placed: wards_placed
        :type wards_placed: int
        """
        self.assists = self._define_number("assists", assists, nullable=True, ge=0)
        self.deaths = self._define_number("deaths", deaths, nullable=True, ge=0)
        self.games_lost = self._define_number(
            "games_lost", games_lost, nullable=True, ge=0
        )
        self.games_played = self._define_number(
            "games_played", games_played, nullable=True, ge=0
        )
        self.games_won = self._define_number(
            "games_won", games_won, nullable=True, ge=0
        )
        self.kill_counters = self._define_object(
            kill_counters, LoLPlayerTotalKillCounters
        )
        self.kills = self._define_number("kills", kills, nullable=True, ge=0)
        self.kills_series = self._define_object(kills_series, LoLKillsSeries)
        self.matches_lost = self._define_number(
            "matches_lost", matches_lost, nullable=True, ge=0
        )
        self.matches_played = self._define_number(
            "matches_played", matches_played, nullable=True, ge=0
        )
        self.matches_won = self._define_number(
            "matches_won", matches_won, nullable=True, ge=0
        )
        self.wards_placed = self._define_number(
            "wards_placed", wards_placed, nullable=True, ge=0
        )
