# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .lo_l_event_inhibitor_value import LoLEventInhibitorValue
from .lo_l_team_color import LoLTeamColor


@JsonMap({})
class LoLEventInhibitorObject(BaseModel):
    """LoLEventInhibitorObject

    :param name: name
    :type name: LoLEventInhibitorValue
    :param side: side
    :type side: LoLTeamColor
    """

    def __init__(self, name: LoLEventInhibitorValue, side: LoLTeamColor):
        """LoLEventInhibitorObject

        :param name: name
        :type name: LoLEventInhibitorValue
        :param side: side
        :type side: LoLTeamColor
        """
        self.name = self._enum_matching(name, LoLEventInhibitorValue.list(), "name")
        self.side = self._enum_matching(side, LoLTeamColor.list(), "side")
