# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class LoLKillsSeries(BaseModel):
    """LoLKillsSeries

    :param double_kills: double_kills
    :type double_kills: int
    :param penta_kills: penta_kills
    :type penta_kills: int
    :param quadra_kills: quadra_kills
    :type quadra_kills: int
    :param triple_kills: triple_kills
    :type triple_kills: int
    """

    def __init__(
        self, double_kills: int, penta_kills: int, quadra_kills: int, triple_kills: int
    ):
        """LoLKillsSeries

        :param double_kills: double_kills
        :type double_kills: int
        :param penta_kills: penta_kills
        :type penta_kills: int
        :param quadra_kills: quadra_kills
        :type quadra_kills: int
        :param triple_kills: triple_kills
        :type triple_kills: int
        """
        self.double_kills = self._define_number(
            "double_kills", double_kills, nullable=True, ge=0
        )
        self.penta_kills = self._define_number(
            "penta_kills", penta_kills, nullable=True, ge=0
        )
        self.quadra_kills = self._define_number(
            "quadra_kills", quadra_kills, nullable=True, ge=0
        )
        self.triple_kills = self._define_number(
            "triple_kills", triple_kills, nullable=True, ge=0
        )
