# This file was generated by liblab | https://liblab.com/

from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"id_": "id"})
class LoLChampion(BaseModel):
    """LoLChampion

    :param armor: armor
    :type armor: float
    :param armorperlevel: armorperlevel
    :type armorperlevel: float
    :param attackdamage: attackdamage
    :type attackdamage: float
    :param attackdamageperlevel: attackdamageperlevel
    :type attackdamageperlevel: float
    :param attackrange: attackrange
    :type attackrange: float
    :param attackspeedoffset: attackspeedoffset
    :type attackspeedoffset: float
    :param attackspeedperlevel: attackspeedperlevel
    :type attackspeedperlevel: float
    :param big_image_url: big_image_url
    :type big_image_url: str
    :param crit: crit
    :type crit: float
    :param critperlevel: critperlevel
    :type critperlevel: float
    :param hp: hp
    :type hp: float
    :param hpperlevel: hpperlevel
    :type hpperlevel: float
    :param hpregen: hpregen
    :type hpregen: float
    :param hpregenperlevel: hpregenperlevel
    :type hpregenperlevel: float
    :param id_: id_
    :type id_: int
    :param image_url: image_url
    :type image_url: str
    :param movespeed: movespeed
    :type movespeed: float
    :param mp: mp
    :type mp: float
    :param mpperlevel: mpperlevel
    :type mpperlevel: float
    :param mpregen: mpregen
    :type mpregen: float
    :param mpregenperlevel: mpregenperlevel
    :type mpregenperlevel: float
    :param name: name
    :type name: str
    :param spellblock: spellblock
    :type spellblock: float
    :param spellblockperlevel: spellblockperlevel
    :type spellblockperlevel: float
    :param videogame_versions: Array of of video game versions (ie. patches) for this resource
    :type videogame_versions: List[str]
    """

    def __init__(
        self,
        armor: float,
        armorperlevel: float,
        attackdamage: float,
        attackdamageperlevel: float,
        attackrange: float,
        attackspeedoffset: float,
        attackspeedperlevel: float,
        big_image_url: str,
        crit: float,
        critperlevel: float,
        hp: float,
        hpperlevel: float,
        hpregen: float,
        hpregenperlevel: float,
        id_: int,
        image_url: str,
        movespeed: float,
        mp: float,
        mpperlevel: float,
        mpregen: float,
        mpregenperlevel: float,
        name: str,
        spellblock: float,
        spellblockperlevel: float,
        videogame_versions: List[str],
    ):
        """LoLChampion

        :param armor: armor
        :type armor: float
        :param armorperlevel: armorperlevel
        :type armorperlevel: float
        :param attackdamage: attackdamage
        :type attackdamage: float
        :param attackdamageperlevel: attackdamageperlevel
        :type attackdamageperlevel: float
        :param attackrange: attackrange
        :type attackrange: float
        :param attackspeedoffset: attackspeedoffset
        :type attackspeedoffset: float
        :param attackspeedperlevel: attackspeedperlevel
        :type attackspeedperlevel: float
        :param big_image_url: big_image_url
        :type big_image_url: str
        :param crit: crit
        :type crit: float
        :param critperlevel: critperlevel
        :type critperlevel: float
        :param hp: hp
        :type hp: float
        :param hpperlevel: hpperlevel
        :type hpperlevel: float
        :param hpregen: hpregen
        :type hpregen: float
        :param hpregenperlevel: hpregenperlevel
        :type hpregenperlevel: float
        :param id_: id_
        :type id_: int
        :param image_url: image_url
        :type image_url: str
        :param movespeed: movespeed
        :type movespeed: float
        :param mp: mp
        :type mp: float
        :param mpperlevel: mpperlevel
        :type mpperlevel: float
        :param mpregen: mpregen
        :type mpregen: float
        :param mpregenperlevel: mpregenperlevel
        :type mpregenperlevel: float
        :param name: name
        :type name: str
        :param spellblock: spellblock
        :type spellblock: float
        :param spellblockperlevel: spellblockperlevel
        :type spellblockperlevel: float
        :param videogame_versions: Array of of video game versions (ie. patches) for this resource
        :type videogame_versions: List[str]
        """
        self.armor = self._define_number("armor", armor, ge=0)
        self.armorperlevel = self._define_number("armorperlevel", armorperlevel, ge=0)
        self.attackdamage = self._define_number("attackdamage", attackdamage, ge=0)
        self.attackdamageperlevel = self._define_number(
            "attackdamageperlevel", attackdamageperlevel, ge=0
        )
        self.attackrange = self._define_number("attackrange", attackrange, ge=0)
        self.attackspeedoffset = self._define_number(
            "attackspeedoffset", attackspeedoffset, nullable=True
        )
        self.attackspeedperlevel = self._define_number(
            "attackspeedperlevel", attackspeedperlevel, ge=0
        )
        self.big_image_url = big_image_url
        self.crit = self._define_number("crit", crit, ge=0)
        self.critperlevel = self._define_number("critperlevel", critperlevel, ge=0)
        self.hp = self._define_number("hp", hp, ge=0)
        self.hpperlevel = self._define_number("hpperlevel", hpperlevel, ge=0)
        self.hpregen = self._define_number("hpregen", hpregen, ge=0)
        self.hpregenperlevel = self._define_number(
            "hpregenperlevel", hpregenperlevel, ge=0
        )
        self.id_ = self._define_number("id_", id_, ge=1)
        self.image_url = image_url
        self.movespeed = self._define_number("movespeed", movespeed, ge=0)
        self.mp = self._define_number("mp", mp, ge=0)
        self.mpperlevel = self._define_number("mpperlevel", mpperlevel, ge=0)
        self.mpregen = self._define_number("mpregen", mpregen, ge=0)
        self.mpregenperlevel = self._define_number(
            "mpregenperlevel", mpregenperlevel, ge=0
        )
        self.name = name
        self.spellblock = self._define_number("spellblock", spellblock, ge=0)
        self.spellblockperlevel = self._define_number(
            "spellblockperlevel", spellblockperlevel, ge=0
        )
        self.videogame_versions = videogame_versions
