# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .lo_l_team_ratios import LoLTeamRatios


@JsonMap({})
class LoLTeamAverages(BaseModel):
    """LoLTeamAverages

    :param assists: assists
    :type assists: float
    :param baron_kills: baron_kills
    :type baron_kills: float
    :param deaths: deaths
    :type deaths: float
    :param dragon_kills: dragon_kills
    :type dragon_kills: float
    :param game_length: Duration of the game in seconds. <br/>`null` when the game status is not `finished`
    :type game_length: int
    :param gold_earned: gold_earned
    :type gold_earned: float
    :param herald_kill: herald_kill
    :type herald_kill: float
    :param inhibitor_kills: inhibitor_kills
    :type inhibitor_kills: float
    :param kills: kills
    :type kills: float
    :param ratios: ratios
    :type ratios: LoLTeamRatios
    :param total_minions_killed: total_minions_killed
    :type total_minions_killed: float
    :param tower_kills: tower_kills
    :type tower_kills: float
    :param voidgrub_kills: The number of voidgrubs killed by a team.
    :type voidgrub_kills: float
    :param wards_placed: wards_placed
    :type wards_placed: float
    """

    def __init__(
        self,
        assists: float,
        baron_kills: float,
        deaths: float,
        dragon_kills: float,
        game_length: int,
        gold_earned: float,
        herald_kill: float,
        inhibitor_kills: float,
        kills: float,
        ratios: LoLTeamRatios,
        total_minions_killed: float,
        tower_kills: float,
        voidgrub_kills: float,
        wards_placed: float,
    ):
        """LoLTeamAverages

        :param assists: assists
        :type assists: float
        :param baron_kills: baron_kills
        :type baron_kills: float
        :param deaths: deaths
        :type deaths: float
        :param dragon_kills: dragon_kills
        :type dragon_kills: float
        :param game_length: Duration of the game in seconds. <br/>`null` when the game status is not `finished`
        :type game_length: int
        :param gold_earned: gold_earned
        :type gold_earned: float
        :param herald_kill: herald_kill
        :type herald_kill: float
        :param inhibitor_kills: inhibitor_kills
        :type inhibitor_kills: float
        :param kills: kills
        :type kills: float
        :param ratios: ratios
        :type ratios: LoLTeamRatios
        :param total_minions_killed: total_minions_killed
        :type total_minions_killed: float
        :param tower_kills: tower_kills
        :type tower_kills: float
        :param voidgrub_kills: The number of voidgrubs killed by a team.
        :type voidgrub_kills: float
        :param wards_placed: wards_placed
        :type wards_placed: float
        """
        self.assists = self._define_number("assists", assists, nullable=True, ge=0)
        self.baron_kills = self._define_number(
            "baron_kills", baron_kills, nullable=True, ge=0
        )
        self.deaths = self._define_number("deaths", deaths, nullable=True, ge=0)
        self.dragon_kills = self._define_number(
            "dragon_kills", dragon_kills, nullable=True, ge=0
        )
        self.game_length = self._define_number(
            "game_length", game_length, nullable=True, ge=0
        )
        self.gold_earned = self._define_number(
            "gold_earned", gold_earned, nullable=True, ge=0
        )
        self.herald_kill = self._define_number(
            "herald_kill", herald_kill, nullable=True, ge=0
        )
        self.inhibitor_kills = self._define_number(
            "inhibitor_kills", inhibitor_kills, nullable=True, ge=0
        )
        self.kills = self._define_number("kills", kills, nullable=True, ge=0)
        self.ratios = self._define_object(ratios, LoLTeamRatios)
        self.total_minions_killed = self._define_number(
            "total_minions_killed", total_minions_killed, nullable=True, ge=0
        )
        self.tower_kills = self._define_number(
            "tower_kills", tower_kills, nullable=True, ge=0
        )
        self.voidgrub_kills = self._define_number(
            "voidgrub_kills", voidgrub_kills, nullable=True, ge=0, le=6
        )
        self.wards_placed = self._define_number(
            "wards_placed", wards_placed, nullable=True, ge=0
        )
