# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .lo_l_team_averages import LoLTeamAverages
from .lo_l_team_stats_totals import LoLTeamStatsTotals


@JsonMap({})
class LoLTotalTeamStat(BaseModel):
    """Total Team's statistics

    :param averages: averages
    :type averages: LoLTeamAverages
    :param games_count: Number of games
    :type games_count: int
    :param totals: totals
    :type totals: LoLTeamStatsTotals
    """

    def __init__(
        self, averages: LoLTeamAverages, games_count: int, totals: LoLTeamStatsTotals
    ):
        """Total Team's statistics

        :param averages: averages
        :type averages: LoLTeamAverages
        :param games_count: Number of games
        :type games_count: int
        :param totals: totals
        :type totals: LoLTeamStatsTotals
        """
        self.averages = self._define_object(averages, LoLTeamAverages)
        self.games_count = self._define_number(
            "games_count", games_count, nullable=True, ge=0
        )
        self.totals = self._define_object(totals, LoLTeamStatsTotals)
