# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .lo_l_team_last_game import LoLTeamLastGame
from .lo_l_banned_champion import LoLBannedChampion
from .lo_l_picked_champion import LoLPickedChampion
from .base_player import BasePlayer
from .lo_l_team_by_serie_stat import LoLTeamBySerieStat


@JsonMap({"id_": "id"})
class LoLStatsForTeamBySerie(BaseModel):
    """Team's aggregated statistics for a serie

    :param acronym: acronym
    :type acronym: str
    :param id_: id_
    :type id_: int
    :param image_url: URL of the team logo
    :type image_url: str
    :param last_games: last_games
    :type last_games: List[LoLTeamLastGame]
    :param location: The team's organization location
    :type location: str
    :param modified_at: modified_at
    :type modified_at: str
    :param most_banned: most_banned
    :type most_banned: List[LoLBannedChampion]
    :param most_banned_against: most_banned_against
    :type most_banned_against: List[LoLBannedChampion]
    :param most_picked: most_picked
    :type most_picked: List[LoLPickedChampion]
    :param name: The name of the team.
    :type name: str
    :param players: players
    :type players: List[BasePlayer]
    :param slug: slug
    :type slug: str
    :param stats: Team's statistics for a serie
    :type stats: LoLTeamBySerieStat
    """

    def __init__(
        self,
        acronym: str,
        id_: int,
        image_url: str,
        last_games: List[LoLTeamLastGame],
        location: str,
        modified_at: str,
        most_banned: List[LoLBannedChampion],
        most_banned_against: List[LoLBannedChampion],
        most_picked: List[LoLPickedChampion],
        name: str,
        players: List[BasePlayer],
        slug: str,
        stats: LoLTeamBySerieStat,
    ):
        """Team's aggregated statistics for a serie

        :param acronym: acronym
        :type acronym: str
        :param id_: id_
        :type id_: int
        :param image_url: URL of the team logo
        :type image_url: str
        :param last_games: last_games
        :type last_games: List[LoLTeamLastGame]
        :param location: The team's organization location
        :type location: str
        :param modified_at: modified_at
        :type modified_at: str
        :param most_banned: most_banned
        :type most_banned: List[LoLBannedChampion]
        :param most_banned_against: most_banned_against
        :type most_banned_against: List[LoLBannedChampion]
        :param most_picked: most_picked
        :type most_picked: List[LoLPickedChampion]
        :param name: The name of the team.
        :type name: str
        :param players: players
        :type players: List[BasePlayer]
        :param slug: slug
        :type slug: str
        :param stats: Team's statistics for a serie
        :type stats: LoLTeamBySerieStat
        """
        self.acronym = self._define_str("acronym", acronym, nullable=True)
        self.id_ = self._define_number("id_", id_, ge=1)
        self.image_url = self._define_str("image_url", image_url, nullable=True)
        self.last_games = self._define_list(last_games, LoLTeamLastGame)
        self.location = self._define_str("location", location, nullable=True)
        self.modified_at = self._define_str("modified_at", modified_at, min_length=1)
        self.most_banned = self._define_list(most_banned, LoLBannedChampion)
        self.most_banned_against = self._define_list(
            most_banned_against, LoLBannedChampion
        )
        self.most_picked = self._define_list(most_picked, LoLPickedChampion)
        self.name = name
        self.players = self._define_list(players, BasePlayer)
        self.slug = self._define_str(
            "slug", slug, nullable=True, pattern="^[a-z0-9_-]+$", min_length=1
        )
        self.stats = self._define_object(stats, LoLTeamBySerieStat)
