# This file was generated by liblab | https://liblab.com/

from enum import Enum


class LoLEventType(Enum):
    """An enumeration representing different categories.

    :cvar BARONNASHORKILL: "baron_nashor_kill"
    :vartype BARONNASHORKILL: str
    :cvar DRAKEKILL: "drake_kill"
    :vartype DRAKEKILL: str
    :cvar INHIBITORKILL: "inhibitor_kill"
    :vartype INHIBITORKILL: str
    :cvar OTHER: "other"
    :vartype OTHER: str
    :cvar PLAYERKILL: "player_kill"
    :vartype PLAYERKILL: str
    :cvar RIFTHERALDKILL: "rift_herald_kill"
    :vartype RIFTHERALDKILL: str
    :cvar SUICIDE: "suicide"
    :vartype SUICIDE: str
    :cvar TOWERKILL: "tower_kill"
    :vartype TOWERKILL: str
    :cvar VOIDGRUBKILL: "voidgrub_kill"
    :vartype VOIDGRUBKILL: str
    """

    BARONNASHORKILL = "baron_nashor_kill"
    DRAKEKILL = "drake_kill"
    INHIBITORKILL = "inhibitor_kill"
    OTHER = "other"
    PLAYERKILL = "player_kill"
    RIFTHERALDKILL = "rift_herald_kill"
    SUICIDE = "suicide"
    TOWERKILL = "tower_kill"
    VOIDGRUBKILL = "voidgrub_kill"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, LoLEventType._member_map_.values()))
