# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class MatchLive(BaseModel):
    """MatchLive

    :param opens_at: opens_at
    :type opens_at: str
    :param supported: Whether live is supported
    :type supported: bool
    :param url: url
    :type url: str
    """

    def __init__(self, opens_at: str, supported: bool, url: str):
        """MatchLive

        :param opens_at: opens_at
        :type opens_at: str
        :param supported: Whether live is supported
        :type supported: bool
        :param url: url
        :type url: str
        """
        self.opens_at = self._define_str(
            "opens_at", opens_at, nullable=True, min_length=1
        )
        self.supported = supported
        self.url = self._define_str("url", url, nullable=True)
