# This file was generated by liblab | https://liblab.com/

from enum import Enum


class MatchType(Enum):
    """An enumeration representing different categories.

    :cvar ALLGAMESPLAYED: "all_games_played"
    :vartype ALLGAMESPLAYED: str
    :cvar BESTOF: "best_of"
    :vartype BESTOF: str
    :cvar CUSTOM: "custom"
    :vartype CUSTOM: str
    :cvar FIRSTTO: "first_to"
    :vartype FIRSTTO: str
    :cvar OWBESTOF: "ow_best_of"
    :vartype OWBESTOF: str
    :cvar REDBULLHOMEGROUND: "red_bull_home_ground"
    :vartype REDBULLHOMEGROUND: str
    """

    ALLGAMESPLAYED = "all_games_played"
    BESTOF = "best_of"
    CUSTOM = "custom"
    FIRSTTO = "first_to"
    OWBESTOF = "ow_best_of"
    REDBULLHOMEGROUND = "red_bull_home_ground"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, MatchType._member_map_.values()))
