# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .ow_hero import OwHero


@JsonMap({})
class OwFavoriteHero(BaseModel):
    """OwFavoriteHero

    :param games_count: Number of games
    :type games_count: int
    :param hero: hero
    :type hero: OwHero
    """

    def __init__(self, games_count: int, hero: OwHero):
        """OwFavoriteHero

        :param games_count: Number of games
        :type games_count: int
        :param hero: hero
        :type hero: OwHero
        """
        self.games_count = self._define_number("games_count", games_count, ge=0)
        self.hero = self._define_object(hero, OwHero)
