# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .ow_hero_role import OwHeroRole


@JsonMap({"id_": "id"})
class OwHero(BaseModel):
    """OwHero

    :param difficulty: difficulty
    :type difficulty: int
    :param id_: id_
    :type id_: int
    :param image_url: image_url
    :type image_url: str
    :param name: name
    :type name: str
    :param portrait_url: portrait_url
    :type portrait_url: str
    :param real_name: real_name
    :type real_name: str
    :param role: role
    :type role: OwHeroRole
    :param slug: slug
    :type slug: str
    """

    def __init__(
        self,
        difficulty: int,
        id_: int,
        image_url: str,
        name: str,
        portrait_url: str,
        real_name: str,
        role: OwHeroRole,
        slug: str,
    ):
        """OwHero

        :param difficulty: difficulty
        :type difficulty: int
        :param id_: id_
        :type id_: int
        :param image_url: image_url
        :type image_url: str
        :param name: name
        :type name: str
        :param portrait_url: portrait_url
        :type portrait_url: str
        :param real_name: real_name
        :type real_name: str
        :param role: role
        :type role: OwHeroRole
        :param slug: slug
        :type slug: str
        """
        self.difficulty = self._define_number("difficulty", difficulty, ge=1)
        self.id_ = self._define_number("id_", id_, ge=1)
        self.image_url = image_url
        self.name = name
        self.portrait_url = portrait_url
        self.real_name = real_name
        self.role = self._enum_matching(role, OwHeroRole.list(), "role")
        self.slug = self._define_str(
            "slug", slug, pattern="^[a-z0-9_-]+$", min_length=1
        )
