# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class OwPlayerGameTotalsForGame(BaseModel):
    """OwPlayerGameTotalsForGame

    :param average_time_to_charge_ultimate: average_time_to_charge_ultimate
    :type average_time_to_charge_ultimate: float
    :param damage_done: damage_done
    :type damage_done: float
    :param deaths: deaths
    :type deaths: float
    :param destructions: destructions
    :type destructions: float
    :param eliminations: eliminations
    :type eliminations: int
    :param healing_done: healing_done
    :type healing_done: float
    :param kills: kills
    :type kills: float
    :param map_draw: map_draw
    :type map_draw: float
    :param map_lost: map_lost
    :type map_lost: float
    :param map_won: map_won
    :type map_won: float
    :param resurrections: resurrections
    :type resurrections: float
    :param ultimates: ultimates
    :type ultimates: float
    """

    def __init__(
        self,
        average_time_to_charge_ultimate: float,
        damage_done: float,
        deaths: float,
        destructions: float,
        eliminations: int,
        healing_done: float,
        kills: float,
        map_draw: float,
        map_lost: float,
        map_won: float,
        resurrections: float,
        ultimates: float,
    ):
        """OwPlayerGameTotalsForGame

        :param average_time_to_charge_ultimate: average_time_to_charge_ultimate
        :type average_time_to_charge_ultimate: float
        :param damage_done: damage_done
        :type damage_done: float
        :param deaths: deaths
        :type deaths: float
        :param destructions: destructions
        :type destructions: float
        :param eliminations: eliminations
        :type eliminations: int
        :param healing_done: healing_done
        :type healing_done: float
        :param kills: kills
        :type kills: float
        :param map_draw: map_draw
        :type map_draw: float
        :param map_lost: map_lost
        :type map_lost: float
        :param map_won: map_won
        :type map_won: float
        :param resurrections: resurrections
        :type resurrections: float
        :param ultimates: ultimates
        :type ultimates: float
        """
        self.average_time_to_charge_ultimate = self._define_number(
            "average_time_to_charge_ultimate",
            average_time_to_charge_ultimate,
            nullable=True,
            ge=0,
        )
        self.damage_done = self._define_number(
            "damage_done", damage_done, nullable=True, ge=0
        )
        self.deaths = self._define_number("deaths", deaths, nullable=True, ge=0)
        self.destructions = self._define_number(
            "destructions", destructions, nullable=True, ge=0
        )
        self.eliminations = self._define_number(
            "eliminations", eliminations, nullable=True, ge=0
        )
        self.healing_done = self._define_number(
            "healing_done", healing_done, nullable=True, ge=0
        )
        self.kills = self._define_number("kills", kills, nullable=True, ge=0)
        self.map_draw = self._define_number("map_draw", map_draw, nullable=True, ge=0)
        self.map_lost = self._define_number("map_lost", map_lost, nullable=True, ge=0)
        self.map_won = self._define_number("map_won", map_won, nullable=True, ge=0)
        self.resurrections = self._define_number(
            "resurrections", resurrections, nullable=True, ge=0
        )
        self.ultimates = self._define_number(
            "ultimates", ultimates, nullable=True, ge=0
        )
