# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class OwPlayer10MinAverages(BaseModel):
    """OwPlayer10MinAverages

    :param damage_done: damage_done
    :type damage_done: float
    :param deaths: deaths
    :type deaths: float
    :param destructions: destructions
    :type destructions: float
    :param eliminations: eliminations
    :type eliminations: float
    :param healing_done: healing_done
    :type healing_done: float
    :param kills: kills
    :type kills: float
    :param resurrections: resurrections
    :type resurrections: float
    :param ultimates: ultimates
    :type ultimates: float
    """

    def __init__(
        self,
        damage_done: float,
        deaths: float,
        destructions: float,
        eliminations: float,
        healing_done: float,
        kills: float,
        resurrections: float,
        ultimates: float,
    ):
        """OwPlayer10MinAverages

        :param damage_done: damage_done
        :type damage_done: float
        :param deaths: deaths
        :type deaths: float
        :param destructions: destructions
        :type destructions: float
        :param eliminations: eliminations
        :type eliminations: float
        :param healing_done: healing_done
        :type healing_done: float
        :param kills: kills
        :type kills: float
        :param resurrections: resurrections
        :type resurrections: float
        :param ultimates: ultimates
        :type ultimates: float
        """
        self.damage_done = self._define_number(
            "damage_done", damage_done, nullable=True, ge=0
        )
        self.deaths = self._define_number("deaths", deaths, nullable=True, ge=0)
        self.destructions = self._define_number(
            "destructions", destructions, nullable=True, ge=0
        )
        self.eliminations = self._define_number(
            "eliminations", eliminations, nullable=True, ge=0
        )
        self.healing_done = self._define_number(
            "healing_done", healing_done, nullable=True, ge=0
        )
        self.kills = self._define_number("kills", kills, nullable=True, ge=0)
        self.resurrections = self._define_number(
            "resurrections", resurrections, nullable=True, ge=0
        )
        self.ultimates = self._define_number(
            "ultimates", ultimates, nullable=True, ge=0
        )
