# This file was generated by liblab | https://liblab.com/

from typing import Union
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.one_of_base_model import OneOfBaseModel


@JsonMap({})
class Page2(BaseModel):
    """Page2

    :param number: number, defaults to None
    :type number: int, optional
    :param size: size, defaults to None
    :type size: int, optional
    """

    def __init__(self, number: int = None, size: int = None):
        """Page2

        :param number: number, defaults to None
        :type number: int, optional
        :param size: size, defaults to None
        :type size: int, optional
        """
        if number is not None:
            self.number = self._define_number("number", number, ge=1)
        if size is not None:
            self.size = self._define_number("size", size, ge=1, le=100)


class PageGuard(OneOfBaseModel):
    class_list = {"int": int, "Page2": Page2}


Page = Union[int, Page2]
