# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class SearchOverValorantWeapons(BaseModel):
    """SearchOverValorantWeapons

    :param name: Name of the weapon, defaults to None
    :type name: str, optional
    """

    def __init__(self, name: str = None):
        """SearchOverValorantWeapons

        :param name: Name of the weapon, defaults to None
        :type name: str, optional
        """
        if name is not None:
            self.name = name
