# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class SearchOverValorantAgents(BaseModel):
    """SearchOverValorantAgents

    :param name: Name of the agent, defaults to None
    :type name: str, optional
    """

    def __init__(self, name: str = None):
        """SearchOverValorantAgents

        :param name: Name of the agent, defaults to None
        :type name: str, optional
        """
        if name is not None:
            self.name = name
