# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class SearchOverValorantMaps(BaseModel):
    """SearchOverValorantMaps

    :param name: Name of the map, defaults to None
    :type name: str, optional
    :param slug: Human-readable identifier of the map, defaults to None
    :type slug: str, optional
    """

    def __init__(self, name: str = None, slug: str = None):
        """SearchOverValorantMaps

        :param name: Name of the map, defaults to None
        :type name: str, optional
        :param slug: Human-readable identifier of the map, defaults to None
        :type slug: str, optional
        """
        if name is not None:
            self.name = name
        if slug is not None:
            self.slug = self._define_str(
                "slug", slug, pattern="^[a-z0-9_-]+$", min_length=1
            )
