# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class SearchOverDota2Items(BaseModel):
    """SearchOverDota2Items

    :param name: name, defaults to None
    :type name: str, optional
    """

    def __init__(self, name: str = None):
        """SearchOverDota2Items

        :param name: name, defaults to None
        :type name: str, optional
        """
        if name is not None:
            self.name = self._define_str(
                "name", name, pattern="^[a-z0-9_-]+$", min_length=1
            )
