# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class ShortVideogameVersion(BaseModel):
    """ShortVideogameVersion

    :param current: Whether this videogame version is current
    :type current: bool
    :param name: name
    :type name: str
    """

    def __init__(self, current: bool, name: str):
        """ShortVideogameVersion

        :param current: Whether this videogame version is current
        :type current: bool
        :param name: name
        :type name: str
        """
        self.current = current
        self.name = self._define_str(
            "name", name, pattern="^[0-9]+\.[0-9]+(\.[0-9]+)?$"
        )
