# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .valorant_kill_event_details import ValorantKillEventDetails
from .valorant_event_type import ValorantEventType


@JsonMap({"type_": "type"})
class ValorantKillEvent(BaseModel):
    """ValorantKillEvent

    :param kill: kill
    :type kill: ValorantKillEventDetails
    :param number: number
    :type number: int
    :param timestamp: Time elapsed since the beginning of round, in seconds
    :type timestamp: int
    :param type_: type_
    :type type_: ValorantEventType
    """

    def __init__(
        self,
        kill: ValorantKillEventDetails,
        number: int,
        timestamp: int,
        type_: ValorantEventType,
    ):
        """ValorantKillEvent

        :param kill: kill
        :type kill: ValorantKillEventDetails
        :param number: number
        :type number: int
        :param timestamp: Time elapsed since the beginning of round, in seconds
        :type timestamp: int
        :param type_: type_
        :type type_: ValorantEventType
        """
        self.kill = self._define_object(kill, ValorantKillEventDetails)
        self.number = self._define_number("number", number, ge=1)
        self.timestamp = self._define_number("timestamp", timestamp, ge=0)
        self.type_ = self._enum_matching(type_, ValorantEventType.list(), "type_")
