# This file was generated by liblab | https://liblab.com/

from enum import Enum


class ValorantPlayerShield(Enum):
    """An enumeration representing different categories.

    :cvar HEAVYSHIELD: "heavy_shield"
    :vartype HEAVYSHIELD: str
    :cvar LIGHTSHIELD: "light_shield"
    :vartype LIGHTSHIELD: str
    :cvar NOSHIELD: "no_shield"
    :vartype NOSHIELD: str
    """

    HEAVYSHIELD = "heavy_shield"
    LIGHTSHIELD = "light_shield"
    NOSHIELD = "no_shield"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, ValorantPlayerShield._member_map_.values()))
