# This file was generated by liblab | https://liblab.com/

from enum import Enum
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class AbilityType(Enum):
    """An enumeration representing different categories.

    :cvar ABILITYONE: "ability_one"
    :vartype ABILITYONE: str
    :cvar ABILITYTWO: "ability_two"
    :vartype ABILITYTWO: str
    :cvar GRENADEABILITY: "grenade_ability"
    :vartype GRENADEABILITY: str
    :cvar ULTIMATEABILITY: "ultimate_ability"
    :vartype ULTIMATEABILITY: str
    """

    ABILITYONE = "ability_one"
    ABILITYTWO = "ability_two"
    GRENADEABILITY = "grenade_ability"
    ULTIMATEABILITY = "ultimate_ability"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, AbilityType._member_map_.values()))


@JsonMap({"id_": "id"})
class ValorantAbility(BaseModel):
    """ValorantAbility

    :param ability_type: Ability type
    :type ability_type: AbilityType
    :param creds: Credit cost of the ability
    :type creds: float
    :param id_: ID of the ability
    :type id_: int
    :param image_url: URL to an image of the ability
    :type image_url: str
    :param name: Name of the ability
    :type name: str
    :param videogame_versions: Array of of video game versions (ie. patches) for this resource
    :type videogame_versions: List[str]
    """

    def __init__(
        self,
        ability_type: AbilityType,
        creds: float,
        id_: int,
        image_url: str,
        name: str,
        videogame_versions: List[str],
    ):
        """ValorantAbility

        :param ability_type: Ability type
        :type ability_type: AbilityType
        :param creds: Credit cost of the ability
        :type creds: float
        :param id_: ID of the ability
        :type id_: int
        :param image_url: URL to an image of the ability
        :type image_url: str
        :param name: Name of the ability
        :type name: str
        :param videogame_versions: Array of of video game versions (ie. patches) for this resource
        :type videogame_versions: List[str]
        """
        self.ability_type = self._enum_matching(
            ability_type, AbilityType.list(), "ability_type"
        )
        self.creds = self._define_number("creds", creds, nullable=True, ge=0)
        self.id_ = self._define_number("id_", id_, ge=1)
        self.image_url = self._define_str("image_url", image_url, nullable=True)
        self.name = name
        self.videogame_versions = videogame_versions
