# This file was generated by liblab | https://liblab.com/

from enum import Enum


class ValorantEventType(Enum):
    """An enumeration representing different categories.

    :cvar KILL: "kill"
    :vartype KILL: str
    :cvar SPIKEDEFUSED: "spike_defused"
    :vartype SPIKEDEFUSED: str
    :cvar SPIKEPLANTED: "spike_planted"
    :vartype SPIKEPLANTED: str
    """

    KILL = "kill"
    SPIKEDEFUSED = "spike_defused"
    SPIKEPLANTED = "spike_planted"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, ValorantEventType._member_map_.values()))
