# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .base_valorant_agent import BaseValorantAgent


@JsonMap({"id_": "id"})
class ValorantEventPlayer(BaseModel):
    """ValorantEventPlayer

    :param agent: agent
    :type agent: BaseValorantAgent
    :param id_: ID of the player
    :type id_: int
    :param name: Professional name of the player
    :type name: str
    """

    def __init__(self, agent: BaseValorantAgent, id_: int, name: str):
        """ValorantEventPlayer

        :param agent: agent
        :type agent: BaseValorantAgent
        :param id_: ID of the player
        :type id_: int
        :param name: Professional name of the player
        :type name: str
        """
        self.agent = self._define_object(agent, BaseValorantAgent)
        self.id_ = self._define_number("id_", id_, ge=1)
        self.name = name
