# This file was generated by liblab | https://liblab.com/

from enum import Enum


class ValorantGameRoundOutcome(Enum):
    """An enumeration representing different categories.

    :cvar ATTACKTIMEOUT: "attack_timeout"
    :vartype ATTACKTIMEOUT: str
    :cvar ATTACKERSELIMINATED: "attackers_eliminated"
    :vartype ATTACKERSELIMINATED: str
    :cvar DEFENDERSELIMINATED: "defenders_eliminated"
    :vartype DEFENDERSELIMINATED: str
    :cvar SPIKEDEFUSED: "spike_defused"
    :vartype SPIKEDEFUSED: str
    :cvar SPIKEEXPLODED: "spike_exploded"
    :vartype SPIKEEXPLODED: str
    """

    ATTACKTIMEOUT = "attack_timeout"
    ATTACKERSELIMINATED = "attackers_eliminated"
    DEFENDERSELIMINATED = "defenders_eliminated"
    SPIKEDEFUSED = "spike_defused"
    SPIKEEXPLODED = "spike_exploded"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, ValorantGameRoundOutcome._member_map_.values())
        )
