# This file was generated by liblab | https://liblab.com/

from enum import Enum


class ValorantAbilityType(Enum):
    """An enumeration representing different categories.

    :cvar ABILITYONE: "ability_one"
    :vartype ABILITYONE: str
    :cvar ABILITYTWO: "ability_two"
    :vartype ABILITYTWO: str
    :cvar GRENADEABILITY: "grenade_ability"
    :vartype GRENADEABILITY: str
    :cvar ULTIMATEABILITY: "ultimate_ability"
    :vartype ULTIMATEABILITY: str
    """

    ABILITYONE = "ability_one"
    ABILITYTWO = "ability_two"
    GRENADEABILITY = "grenade_ability"
    ULTIMATEABILITY = "ultimate_ability"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, ValorantAbilityType._member_map_.values()))
