# This file was generated by liblab | https://liblab.com/

from typing import Union
from .utils.one_of_base_model import OneOfBaseModel


class VideogameVersionOrAllGuard(OneOfBaseModel):
    class_list = {"str": str, "any": any, "any": any}


VideogameVersionOrAll = Union[str, any, any]
