# This file was generated by liblab | https://liblab.com/

from enum import Enum


class VideogameSlug(Enum):
    """An enumeration representing different categories.

    :cvar CODMW: "cod-mw"
    :vartype CODMW: str
    :cvar CSGO: "cs-go"
    :vartype CSGO: str
    :cvar DOTA2: "dota-2"
    :vartype DOTA2: str
    :cvar EBASKETBALL: "e-basketball"
    :vartype EBASKETBALL: str
    :cvar ECRICKET: "e-cricket"
    :vartype ECRICKET: str
    :cvar ESOCCER: "e-soccer"
    :vartype ESOCCER: str
    :cvar FIFA: "fifa"
    :vartype FIFA: str
    :cvar KOG: "kog"
    :vartype KOG: str
    :cvar LEAGUEOFLEGENDS: "league-of-legends"
    :vartype LEAGUEOFLEGENDS: str
    :cvar LOLWILDRIFT: "lol-wild-rift"
    :vartype LOLWILDRIFT: str
    :cvar OW: "ow"
    :vartype OW: str
    :cvar PUBG: "pubg"
    :vartype PUBG: str
    :cvar R6SIEGE: "r6-siege"
    :vartype R6SIEGE: str
    :cvar RL: "rl"
    :vartype RL: str
    :cvar STARCRAFT2: "starcraft-2"
    :vartype STARCRAFT2: str
    :cvar STARCRAFTBROODWAR: "starcraft-brood-war"
    :vartype STARCRAFTBROODWAR: str
    :cvar VALORANT: "valorant"
    :vartype VALORANT: str
    """

    CODMW = "cod-mw"
    CSGO = "cs-go"
    DOTA2 = "dota-2"
    EBASKETBALL = "e-basketball"
    ECRICKET = "e-cricket"
    ESOCCER = "e-soccer"
    FIFA = "fifa"
    KOG = "kog"
    LEAGUEOFLEGENDS = "league-of-legends"
    LOLWILDRIFT = "lol-wild-rift"
    OW = "ow"
    PUBG = "pubg"
    R6SIEGE = "r6-siege"
    RL = "rl"
    STARCRAFT2 = "starcraft-2"
    STARCRAFTBROODWAR = "starcraft-brood-war"
    VALORANT = "valorant"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, VideogameSlug._member_map_.values()))
